Repository opensearch-project/security, pull requests merged in 2020-01, with the labels that each got.

#192 Add support for codecov coverage
  .github/workflows/ci.yml
  README.md
  pom.xml
Labels: maintenance

#191 Remove security-parent dependency
  .github/workflows/ci.yml
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  pom.xml
Labels: maintenance

#201 Updating release note and build script for opendistro 1.4
  build.gradle
  opendistro-elasticsearch-security.release-notes
Labels: release

#200 Add Account API to enable users to change their own password
  src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AuthTokenProcessorAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/Endpoint.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/FlushCacheApiAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/InternalUsersApiAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/OpenDistroSecurityConfigAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/OpenDistroSecurityRestApiActions.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RestApiPrivilegesEvaluator.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/TenantsApiAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/support/Utils.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AccountValidator.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/CredentialsValidator.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/InternalUsersValidator.java
  src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiTest.java
  src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RestApiPrivilegesEvaluatorTest.java
  src/test/resources/restapi/internal_users.yml
Labels: enhancement
