Repository opensearch-project/security, pull requests merged in 2020-12, with the labels that each got.

#862 Upgrade github CD action to using Environment Files
  .github/workflows/cd.yml
Labels: maintenance

#850 Adding requested tenant to the thread context transient info for consumption
  src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java
Labels: enhancement

#864 Refactor getUserInfoString
  src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java
Labels: maintenance

#866 Use reflection to get reduceOrder, termBytes and format due to java.lang.IllegalAccessError
  src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/DlsFlsValveImpl.java
  src/main/java/org/elasticsearch/search/aggregations/bucket/terms/StringTermsGetter.java
Labels: bug

#872 Update 1.12 release notes
  release-notes/opendistro-for-elasticsearch-security.release-notes-1.12.0.0.md
Labels: maintenance

#877 Use StringJoiner instead of (Immutable)List builder
  src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java
Labels: maintenance

#884 Pull request intake form (PR template)
  .github/pull_request_template.md
Labels: maintenance

#891 Replace InjectedUser with User during serialization
  src/main/java/com/amazon/opendistroforelasticsearch/security/auth/BackendRegistry.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/auth/UserInjector.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/support/Base64Helper.java
  src/test/java/com/amazon/opendistroforelasticsearch/security/auth/UserInjectorTest.java
Labels: bug

#910 Upgrade Bouncy Castle to 1.67
  pom.xml
Labels: maintenance

#902 Optimize by avoid creating wildcard matchers for every request
  src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/ConfigModelV6.java
  src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/ConfigModelV7.java
Labels: refactoring

#905 Integrate Github CodeQL Analysis into CI
  .github/workflows/ci.yml
Labels: maintenance
