Repository opensearch-project/security, pull requests merged in 2022-03, with the labels that each got.

#1654 configure ML reserved roles and system indices
  securityconfig/roles.yml
  tools/install_demo_configuration.sh
Labels: v1.3.0, backport 1.3

#1656 Remove github DCO action as it has been replaced with a github app
  .github/workflows/dco.yml
Labels: backport 1.3

#1638 securityadmin: Replace TransportClient by RestHighLevelClient
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/action/configupdate/ConfigUpdateNodeResponse.java
  src/main/java/org/opensearch/security/action/configupdate/ConfigUpdateResponse.java
  src/main/java/org/opensearch/security/filter/SecurityRestFilter.java
  src/main/java/org/opensearch/security/rest/SecurityConfigUpdateAction.java
  src/main/java/org/opensearch/security/rest/SecurityWhoAmIAction.java
  src/main/java/org/opensearch/security/support/WildcardMatcher.java
  src/main/java/org/opensearch/security/tools/SecurityAdmin.java
  src/test/java/org/opensearch/security/SecurityAdminIEndpointsTests.java
  src/test/java/org/opensearch/security/SecurityAdminInvalidConfigsTests.java
  src/test/java/org/opensearch/security/SecurityAdminMigrationTests.java
  src/test/java/org/opensearch/security/SecurityAdminTests.java
  src/test/java/org/opensearch/security/auditlog/sink/SinkProviderTLSTest.java
  src/test/java/org/opensearch/security/auditlog/sink/WebhookAuditLogTest.java
Labels: v2.0.0

#1628 Remove standalone admin tools zip file
  build.gradle
Labels: enhancement

#1663 Disable checkstyle until rules are enforced
  .github/workflows/ci.yml
Labels: enhancement

#1541 Add support for DLS Term Lookup Queries
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/configuration/DlsFilterLevelActionHandler.java
  src/main/java/org/opensearch/security/configuration/DlsFlsRequestValve.java
  src/main/java/org/opensearch/security/configuration/DlsFlsValveImpl.java
  src/main/java/org/opensearch/security/configuration/DlsQueryParser.java
  src/main/java/org/opensearch/security/configuration/SecurityFlsDlsIndexSearcherWrapper.java
  src/main/java/org/opensearch/security/filter/SecurityFilter.java
  src/main/java/org/opensearch/security/filter/SecurityRestFilter.java
  src/main/java/org/opensearch/security/privileges/DlsFlsEvaluator.java
  src/main/java/org/opensearch/security/privileges/DocumentAllowList.java
  src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
  src/main/java/org/opensearch/security/privileges/PrivilegesEvaluatorResponse.java
  src/main/java/org/opensearch/security/queries/QueryBuilderTraverser.java
  src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java
  src/main/java/org/opensearch/security/securityconf/ConfigModelV6.java
  src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java
  src/main/java/org/opensearch/security/securityconf/EvaluatedDlsFlsConfig.java
  src/main/java/org/opensearch/security/securityconf/SecurityRoles.java
  src/main/java/org/opensearch/security/support/ConfigConstants.java
  src/main/java/org/opensearch/security/support/ReflectiveAttributeAccessors.java
  src/main/java/org/opensearch/security/transport/SecurityInterceptor.java
  src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java
  src/test/java/org/opensearch/security/dlic/dlsfls/AbstractDlsFlsTest.java
  src/test/java/org/opensearch/security/dlic/dlsfls/DlsTermLookupQueryTest.java
  src/test/java/org/opensearch/security/dlic/dlsfls/DlsTermsLookupAsserts.java
  src/test/java/org/opensearch/security/filter/SecurityFilterTest.java
  src/test/resources/dlsfls/internal_users_tlq.yml
  src/test/resources/dlsfls/roles_mapping_tlq.yml
  src/test/resources/dlsfls/roles_tlq.yml
  src/test/resources/dlsfls/securityconfig_tlq.yml
Labels: v1.3.0, backport 1.3

#1679 Update to most recent verson of jackson-databind
  build.gradle
Labels: security vulnerability

#1691 Revert "Replace opensearch class names with opendistro class names during serialization and restore them back during deserialization (#1278)"
  plugin-security.policy
  src/main/java/org/opensearch/security/support/Base64Helper.java
  src/main/java/org/opensearch/security/user/User.java
Labels: v2.0.0

#1695 Move to version 2.0.0.0
  build.gradle
Labels: v2.0.0

#1690 Add CI check for demo script
  .github/workflows/plugin_install.yml
  build.gradle
Labels: enhancement

#1707 Fix break that was missed during a merge
  .github/workflows/plugin_install.yml
Labels: bug

#1706 Seperate BWC tests into parallel workflow
  .github/workflows/ci.yml
Labels: enhancement

#1705 Move CodeQL into parallel workfow
  .github/workflows/ci.yml
Labels: enhancement

#1710 Upgrade to Gradle 7
  .github/workflows/ci.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: v2.0.0

#1708 Convert Plugin install to only build once
  .github/workflows/plugin_install.yml
Labels: enhancement

#1715 Speeding up tests
  src/test/java/org/opensearch/security/test/AbstractSecurityUnitTest.java
Labels: enhancement

#1709 Remove explict dependency on jackson-databind
  build.gradle
Labels: v2.0.0
