Repository opensearch-project/security, pull requests merged in 2022-11, with the labels that each got.

#2206 Fix windows encoding issues
  .github/workflows/ci.yml
  .github/workflows/code-hygiene.yml
  build.gradle
  spotbugs-include.xml
  src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java
  src/main/java/org/opensearch/security/auditlog/impl/AbstractAuditLog.java
  src/main/java/org/opensearch/security/configuration/ConfigurationLoaderSecurity7.java
  src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java
  src/main/java/org/opensearch/security/support/ConfigHelper.java
  src/main/java/org/opensearch/security/tools/SecurityAdmin.java
  src/test/java/org/opensearch/security/IntegrationTests.java
Labels: windows, backport 2.x, v2.4.0, backport 2.4

#2192 roles yml changes for security-analytics plugin
  config/roles.yml
Labels: backport 2.x, v2.4.0, backport 2.4

#2217 [Backport 2.x] Fix windows encoding issues (#2206)
  .github/workflows/ci.yml
  .github/workflows/code-hygiene.yml
  build.gradle
  spotbugs-include.xml
  src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java
  src/main/java/org/opensearch/security/auditlog/impl/AbstractAuditLog.java
  src/main/java/org/opensearch/security/configuration/ConfigurationLoaderSecurity7.java
  src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java
  src/main/java/org/opensearch/security/support/ConfigHelper.java
  src/main/java/org/opensearch/security/tools/SecurityAdmin.java
  src/test/java/org/opensearch/security/IntegrationTests.java
Labels: v2.4.0

#2231 2.4 Release Notes for Security Plugin
  release-notes/opensearch-security.release-notes-2.4.0.0.md
Labels: backport 2.x, v2.4.0, backport 2.4

#2253 Generalize Backwards Compatibility tests so we can test from any version to any version
  .github/actions/create-bwc-build/action.yaml
  .github/actions/run-bwc-suite/action.yaml
  .github/workflows/bwc-tests.yml
  .github/workflows/ci.yml
  bwc-test/build.gradle
  bwc-test/src/test/java/SecurityBackwardsCompatibilityIT.java
Labels: test fix, backwards-compatibility, windows
