Repository opensearch-project/security, pull requests merged in 2022-04, with the labels that each got.

#1722 Remove sleep when waiting for node close
  src/test/java/org/opensearch/security/test/helper/cluster/ClusterHelper.java
Labels: enhancement

#1758 Add signal/wait model for TestAuditlogImpl
  src/main/java/org/opensearch/security/auditlog/impl/AuditMessage.java
  src/test/java/org/opensearch/security/auditlog/integration/BasicAuditlogTest.java
  src/test/java/org/opensearch/security/auditlog/integration/TestAuditlogImpl.java
  src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java
Labels: bug, test fix

#1782 Add checkstyle for non-inclusive terms
  build.gradle
  config/checkstyle/sun_checks.xml
Labels: enhancement

#1773 Remove advanced_modules_enabled from example
  securityconfig/opensearch.yml.example
Labels: bug, documentation

#1747 Add archive of reports for test/coverage
  .github/workflows/ci.yml
  build.gradle
Labels: enhancement

#1770 Fix 'openserach' typo in roles.yml
  securityconfig/roles.yml
Labels: backport 1.x, backport 1.3, backport 2.0

#1460 Add documentation about integrating APIs with security
  README.md
Labels: documentation
