Repository opensearch-project/security, pull requests merged in 2022-09, with the labels that each got.

#2052 Fix legacy check in SecurityAdmin
  src/main/java/org/opensearch/security/tools/SecurityAdmin.java
  src/test/java/org/opensearch/security/SecurityAdminTests.java
  tools/SECURITY_ADMIN_TESTS.md
Labels: backport 2.0, backport 2.x, backport 2.1, backport 2.2

#2079 Add 2.3.0.0 release notes
  release-notes/opensearch-security.release-notes-2.3.0.0.md
Labels: backport 2.x

#2081 Correct release date to 2022-09-15
  release-notes/opensearch-security.release-notes-2.3.0.0.md
Labels: backport 2.x

#2084 Increment version to 2.4.0.0
  .github/workflows/ci.yml
  build.gradle
  bwc-test/build.gradle
Labels: backport 2.x

#2091 Make ldap pool period and idle time configurable
  src/main/java/com/amazon/dlic/auth/ldap/util/ConfigConstants.java
  src/main/java/com/amazon/dlic/auth/ldap2/LDAPConnectionFactoryFactory.java
Labels: backport 2.x

#2123 Upgrade Kafka Client to 3.0.2
  build.gradle
Labels: backport 1.3, backport 2.x, backport 2.3
