Repository opensearch-project/security, pull requests merged in 2022-06, with the labels that each got.

#1868 Prevent recursive action groups
  src/main/java/org/opensearch/security/dlic/rest/api/ActionGroupsApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/PatchableResourceApiAction.java
  src/test/java/org/opensearch/security/dlic/rest/api/ActionGroupsApiTest.java
Labels: backport 1.3

#1813 Tenant Permissions : added the possibility to specify tenants via parameter
  src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java
  src/test/java/org/opensearch/security/multitenancy/test/MultitenancyTests.java
  src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java
  src/test/resources/multitenancy/internal_users.yml
  src/test/resources/multitenancy/roles.yml
  src/test/resources/multitenancy/roles_mapping.yml
  src/test/resources/multitenancy/roles_tenants.yml
Labels: enhancement

#1814 Add missing settings to plugin allowed list
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/auditlog/config/AuditConfig.java
  src/main/java/org/opensearch/security/auditlog/impl/AuditCategory.java
  src/main/java/org/opensearch/security/auditlog/impl/AuditMessage.java
  src/test/java/org/opensearch/security/auditlog/AbstractAuditlogiUnitTest.java
  src/test/java/org/opensearch/security/auditlog/config/AuditConfigFilterTest.java
  src/test/java/org/opensearch/security/auditlog/integration/BasicAuditlogTest.java
Labels: bug

#1883 Bump version to 2.1.0.0
  .github/workflows/ci.yml
  build.gradle
  bwc-test/build.gradle
  bwc-test/gradle/wrapper/gradle-wrapper.properties
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java
  src/test/java/org/opensearch/security/dlic/rest/api/AbstractRestApiUnitTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/RolesMappingApiTest.java
Labels: v2.1.0

#1897 Adds default roles for Snapshot Management plugin
  securityconfig/roles.yml
Labels: v2.1.0

#1911 Fix build break from cluster manager changes
  src/main/java/org/opensearch/security/dlic/rest/api/MigrateApiAction.java
  src/main/java/org/opensearch/security/tools/SecurityAdmin.java
  src/test/java/org/opensearch/security/test/helper/cluster/ClusterHelper.java
Labels: bug

#1912 Update `org.apache.zookeeper:zookeeper` to `3.7.1`
  build.gradle
Labels: backport 2.x

#1901 Adds release notes for 2.1.0 and revert #1890
  .github/workflows/ci.yml
  build.gradle
  bwc-test/build.gradle
  release-notes/opensearch-security.release-notes-2.1.0.0.md
  src/main/java/com/amazon/dlic/auth/http/kerberos/HTTPSpnegoAuthenticator.java
  src/main/java/com/amazon/dlic/auth/http/saml/SamlFilesystemMetadataResolver.java
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/auditlog/impl/AbstractAuditLog.java
  src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java
  src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java
  src/main/java/org/opensearch/security/ssl/util/SSLRequestHelper.java
  src/main/java/org/opensearch/security/support/PemKeyReader.java
Labels: backport 2.x

#1921 Adds build script for publishing plugin zip
  scripts/build.sh
Labels: backport 2.x
