Repository opensearch-project/security, pull requests merged in 2022-12, with the labels that each got.

#2308 Windows Install Action Fix
  .github/actions/start-opensearch-with-one-plugin/action.yml
  .github/workflows/bwc-tests.yml
  .github/workflows/plugin_install.yml
  tools/install_demo_configuration.bat
  tools/install_demo_configuration.sh
Labels: backport 1.3, backport 2.x, backport 2.4

#2277 Username validation for special characters
  src/main/java/org/opensearch/security/dlic/rest/api/InternalUsersApiAction.java
  src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java
Labels: backport 1.x, backport 1.3, backport 2.x

#2327 Add 2.4.1.0 release notes
  release-notes/opensearch-security.release-notes-2.4.1.0.md
Labels: backport 2.x, backport 2.4

#2328 Add release notes for 1.3.7.0
  release-notes/opensearch-security.release-notes-1.3.7.0.md
Labels: backport 1.3

#2349 [1.x] Fixes CVE-2022-46363
  README.md
  build.gradle
Labels: backport 1.3

#2350 Upgrade CXF to 3.5.5 to address CVE-2022-46363
  build.gradle
Labels: backport 2.x, backport 2.4

#2347 Changing logging type to give warning for basic auth with no creds
  src/main/java/org/opensearch/security/auth/BackendRegistry.java
Labels: backport 2.x
