Repository opensearch-project/security, pull requests merged in 2022-10, with the labels that each got.

#2136 Release notes 1.3.6
  release-notes/opensearch-security.release-notes-1.3.6.0.md
Labels: backport 1.3

#2099 Log deprecation message on legacy ldap pool settings
  src/main/java/com/amazon/dlic/auth/ldap/LdapUser.java
  src/main/java/com/amazon/dlic/auth/ldap/backend/LDAPAuthenticationBackend.java
  src/main/java/com/amazon/dlic/auth/ldap/util/ConfigConstants.java
  src/main/java/com/amazon/dlic/auth/ldap2/LDAPConnectionFactoryFactory.java
  src/main/java/org/opensearch/security/setting/DeprecatedSettings.java
  src/test/java/org/opensearch/security/setting/DeprecatedSettingsTest.java
Labels: backport 2.x

#2094 Point in time security changes
  config/roles.yml
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/privileges/PitPrivilegesEvaluator.java
  src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
  src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java
  src/main/resources/static_config/static_action_groups.yml
  src/test/java/org/opensearch/security/PitIntegrationTests.java
  src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java
  src/test/resources/internal_users.yml
  src/test/resources/roles.yml
  src/test/resources/roles_mapping.yml
Labels: v2.4.0

#2158 add groupId = org.opensearch.plugin
  build.gradle
Labels: backport 2.x, v2.4.0

#2191 Add bcpkix-jdk15on runtimeOnly dependency to read keys with bouncycastle
  build.gradle
  src/test/java/org/opensearch/security/ssl/OpenSSLTest.java
  src/test/java/org/opensearch/security/ssl/SSLTest.java
  src/test/resources/ssl/node-0-pkcs1.key.pem
Labels: backport 2.x

#2161 Add install_demo_configuration Batch script for Windows
  .github/workflows/plugin_install.yml
  tools/install_demo_configuration.bat
Labels: backport 2.x, v2.4.0

#2190 Add CI for Windows and MacOS platforms
  .github/workflows/ci.yml
  src/main/java/org/opensearch/security/support/SecurityUtils.java
  src/test/java/org/opensearch/security/IntegrationTests.java
  src/test/java/org/opensearch/security/auth/limiting/HeapBasedRateTrackerTest.java
  src/test/java/org/opensearch/security/dlic/dlsfls/DlsTest.java
  src/test/java/org/opensearch/security/ssl/OpenSSLTest.java
  src/test/java/org/opensearch/security/support/SecurityUtilsTest.java
Labels: backport 2.x, v2.4.0
