Repository opensearch-project/security, pull requests merged in 2022-05, with the labels that each got.

#1818 Release notes for 1.3.2
  release-notes/opensearch-security.release-notes-1.3.2.0.md
Labels: backport 1.3

#1826 Switch from RC1 to the GA of OpenSearch 2.0
  build.gradle
  bwc-test/build.gradle
  src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java
  src/test/java/org/opensearch/security/ccstest/RemoteReindexTests.java
Labels: backport 2.0

#1844 Add Alerting getFindings cluster permission
  securityconfig/roles.yml
Labels: backport 2.0

#1841 Introduce new API _plugins/_security/ssl/certs
  src/main/java/org/opensearch/security/ssl/rest/SecuritySSLCertsInfoAction.java
  src/test/java/org/opensearch/security/ssl/SecuritySSLCertsInfoActionTests.java
Labels: backport 2.0

#1847 Add default roles for Notifications plugin
  securityconfig/roles.yml
Labels: backport 2.0

#1850 Update `org.springframework:spring-core` to `5.3.20`
  build.gradle
Labels: v2.0.0, backport 2.0, v2.0.0-GeneralAvailability

#1785 JWT: validate issuer and audience (#1780, #1781)
  src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java
  src/test/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticatorTest.java
Labels: v2.1.0
