Repository opensearch-project/security, pull requests merged in 2022-07, with the labels that each got.

#1926 Upgrade netty to 4.1.77
  build.gradle
Labels: backport 2.x

#1945 Force netty-transport-native-unix-common version
  build.gradle
Labels: backport 2.x, backport 2.1

#1937 Create a manually started workflow for bulk run of integration tests
  .github/workflows/integration-tests.yml
  DEVELOPER_GUIDE.md
Labels: test fix

#1939 Incremented version to 2.1.1.
  build.gradle
  bwc-test/build.gradle
Labels: v2.1.1

#1948 Increment version to 2.2.0.0
  .github/workflows/ci.yml
  build.gradle
  bwc-test/build.gradle
Labels: backport 2.x

#1964 Backport cluster evaluation permissions #1885 to 2.0
  src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
  src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java
  src/test/java/org/opensearch/security/IndexTemplateClusterPermissionsCheckTest.java
  src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java
  src/test/resources/internal_users.yml
  src/test/resources/roles.yml
  src/test/resources/roles_mapping.yml
Labels: backport 1.2, backport 1.3, backport 1.1, backport opendistro-1.13
