Repository opensearch-project/security, pull requests merged in 2022-08, with the labels that each got.

#1932 Staging for version increment automation
  .github/workflows/ci.yml
  build.gradle
Labels: backport 2.0, backport 2.x, backport 2.1

#1970 Use Collections.synchronizedSet and Collections.synchronizedMap for r…
  src/main/java/org/opensearch/security/user/User.java
Labels: backport 2.x

#2000 Upgrade jackson databind to 2.13.2.2 to match core's version.properties
  build.gradle
Labels: backport 1.3

#1984 Update release notes for 2.2.0.0
  release-notes/opensearch-security.release-notes-2.2.0.0.md
Labels: backport 2.x, backport 2.2

#2018 Updates matcher to use hasItem
  src/test/java/org/opensearch/security/sanity/tests/SingleClusterSanityIT.java
Labels: backport 2.x, backport 2.2

#1996 Triple audit logging fix (#1995)
  src/main/java/org/opensearch/security/auditlog/sink/Log4JSink.java
Labels: backport 2.x

#2027 Update Gradle to 7.5.1
  bwc-test/gradle/wrapper/gradle-wrapper.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: backport 2.x

#2022 Increment version to 2.3.0.0
  .github/workflows/ci.yml
  build.gradle
  bwc-test/build.gradle
Labels: backport 2.x

#2042 Adding release notes for 1.3.5
  release-notes/opensearch-security.release-notes-1.3.5.0.md
Labels: backport 1.x, backport 1.3
