Repository opensearch-project/security, pull requests merged in 2023-08, with the labels that each got.

#3051 Integrate geospatial ip2geo functionality with security plugin
  config/roles.yml
  tools/install_demo_configuration.bat
  tools/install_demo_configuration.sh
Labels: backport 2.x, v2.10.0

#3083 Bump the version of `kafka` and `spring-kafka-test` (CVE Related)
  build.gradle
Labels: backport 1.3

#3095 Add release notes for 1.3.12.0
  release-notes/opensearch-security.release-notes-1.3.12.0.md
Labels: backport 1.x, backport 1.3

#3077 Make user service use a random password
  build.gradle
  src/main/java/org/opensearch/security/user/UserService.java
  src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java
Labels: backport 2.x, v2.10.0

#3094 Reverse order of setUserInfoInThreadContext and addSecurityRoles to resolve ConcurrentModificationException on bulk request
  src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
Labels: backport 2.x

#3132 Switch CodeQL to assemble artifacts using the same build as the rest of CI
  .github/workflows/ci.yml
Labels: backport 2.x

#3134 Only run the backport job on merged pull requests
  .github/workflows/backport.yml
Labels: backport 2.x

#3136 Fix Document GET with DLS terms query
  src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java
  src/test/java/org/opensearch/security/dlic/dlsfls/DlsTest.java
  src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java
  src/test/resources/dlsfls/roles.yml
  src/test/resources/dlsfls/roles_mapping.yml
Labels: backport 2.x

#3195 Exclude sensitive info from the jackson serialization stacktraces
  src/main/java/org/opensearch/security/DefaultObjectMapper.java
Labels: backport 2.x

#3057 Change password security message
  src/integrationTest/java/org/opensearch/security/api/CreateResetPasswordTest.java
  src/main/java/org/opensearch/security/dlic/rest/validation/PasswordValidator.java
  src/main/java/org/opensearch/security/dlic/rest/validation/RequestContentValidator.java
  src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java
  src/test/java/org/opensearch/security/dlic/rest/validation/PasswordValidatorTest.java
Labels: backport 2.x

#3192 Adds a test to check similarity between audit logs generated from REST layer and TRANSPORT layer
  src/integrationTest/java/org/opensearch/security/rest/WhoAmITests.java
  src/integrationTest/java/org/opensearch/test/framework/audit/AuditLogsRule.java
Labels: backport 2.x

#3226 Implements end-to-end integration tests for Authorization in Rest Layer
  src/integrationTest/java/org/opensearch/security/rest/AuthZinRestLayerTests.java
  src/integrationTest/java/org/opensearch/security/rest/WhoAmITests.java
  src/integrationTest/java/org/opensearch/test/framework/audit/AuditMessagePredicate.java
  src/integrationTest/java/org/opensearch/test/framework/testplugins/AbstractRestHandler.java
  src/integrationTest/java/org/opensearch/test/framework/testplugins/dummy/CustomLegacyTestPlugin.java
  src/integrationTest/java/org/opensearch/test/framework/testplugins/dummy/LegacyRestHandler.java
  src/integrationTest/java/org/opensearch/test/framework/testplugins/dummy/dummyaction/DummyAction.java
  src/integrationTest/java/org/opensearch/test/framework/testplugins/dummy/dummyaction/DummyRequest.java
  src/integrationTest/java/org/opensearch/test/framework/testplugins/dummy/dummyaction/DummyResponse.java
  src/integrationTest/java/org/opensearch/test/framework/testplugins/dummy/dummyaction/TransportDummyAction.java
  src/integrationTest/java/org/opensearch/test/framework/testplugins/dummyprotected/CustomRestProtectedTestPlugin.java
  src/integrationTest/java/org/opensearch/test/framework/testplugins/dummyprotected/ProtectedRoutesRestHandler.java
  src/integrationTest/java/org/opensearch/test/framework/testplugins/dummyprotected/dummyaction/DummyAction.java
  src/integrationTest/java/org/opensearch/test/framework/testplugins/dummyprotected/dummyaction/DummyRequest.java
  src/integrationTest/java/org/opensearch/test/framework/testplugins/dummyprotected/dummyaction/DummyResponse.java
  src/integrationTest/java/org/opensearch/test/framework/testplugins/dummyprotected/dummyaction/TransportDummyAction.java
Labels: backport 2.x

#3239 Update to Gradle 8.3
  bwc-test/gradle/wrapper/gradle-wrapper.jar
  bwc-test/gradle/wrapper/gradle-wrapper.properties
  bwc-test/gradlew
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: dependencies

#3123 [Refactor] Adopt request builder patterns for SecurityRestApiActions for consistency and clarity
  src/main/java/org/opensearch/security/DefaultObjectMapper.java
  src/main/java/org/opensearch/security/dlic/rest/api/AbstractApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/AccountApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/ActionGroupsApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/AllowlistApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/AuditApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/AuthTokenProcessorAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/FlushCacheApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/InternalUsersApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/MigrateApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/MultiTenancyConfigApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/NodesDnApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/PatchableResourceApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/RequestHandler.java
  src/main/java/org/opensearch/security/dlic/rest/api/Responses.java
  src/main/java/org/opensearch/security/dlic/rest/api/RestApiAdminPrivilegesEvaluator.java
  src/main/java/org/opensearch/security/dlic/rest/api/RolesApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/RolesMappingApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/SecurityApiDependencies.java
  src/main/java/org/opensearch/security/dlic/rest/api/SecurityConfigAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/SecurityConfiguration.java
  src/main/java/org/opensearch/security/dlic/rest/api/SecurityRestApiActions.java
  src/main/java/org/opensearch/security/dlic/rest/api/SecuritySSLCertsAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/TenantsApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/ValidateApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/WhitelistApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/support/Utils.java
  src/main/java/org/opensearch/security/dlic/rest/validation/EndpointValidator.java
  src/main/java/org/opensearch/security/dlic/rest/validation/RequestContentValidator.java
  src/main/java/org/opensearch/security/dlic/rest/validation/ValidationResult.java
  src/main/java/org/opensearch/security/securityconf/impl/SecurityDynamicConfiguration.java
  src/test/java/org/opensearch/security/dlic/rest/api/AbstractApiActionValidationTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/AccountApiActionConfigValidationsTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/ActionGroupsApiActionValidationTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/AllowlistApiTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/AuditApiActionTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/AuditApiActionValidationTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/InternalUsersApiActionValidationTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/NodesDnApiActionValidationTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/RequestHandlersBuilderTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/RolesApiActionValidationTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/RolesMappingApiActionValidationTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/RolesMappingApiTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiActionValidationTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/SecurityConfigurationTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/WhitelistApiTest.java
  src/test/java/org/opensearch/security/dlic/rest/validation/EndpointValidatorTest.java
  src/test/java/org/opensearch/security/dlic/rest/validation/RequestContentValidatorTest.java
  src/test/java/org/opensearch/security/ssl/SecuritySSLReloadCertsActionTests.java
  src/test/java/org/opensearch/security/util/FakeRestRequest.java
Labels: backport 2.x, v2.10.0

#3205 Prevent raw request body as output in serialization error messages
  src/main/java/org/opensearch/security/DefaultObjectMapper.java
  src/main/java/org/opensearch/security/NonValidatingObjectMapper.java
Labels: backport 2.x, v2.10.0

#3262 [Refactor] Remove json-path from deps and use JsonPointer instead
  build.gradle
  src/main/java/org/opensearch/security/dlic/rest/api/AuditApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/RolesApiAction.java
  src/test/java/org/opensearch/security/dlic/rest/api/AuditApiActionRequestContentValidatorTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/RolesApiActionRequestContentValidatorTest.java
  src/test/java/org/opensearch/security/ssl/SecuritySSLReloadCertsActionTests.java
Labels: backport 2.x
