Repository opensearch-project/security, pull requests merged in 2023-05, with the labels that each got.

#2599 Identify extension Transport requests and permit handshake and extension registration actions
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/support/ConfigConstants.java
  src/main/java/org/opensearch/security/support/HeaderHelper.java
  src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java
Labels: backport 2.x

#2738 Update to Gradle 8.1.1
  bwc-test/gradle/wrapper/gradle-wrapper.jar
  bwc-test/gradle/wrapper/gradle-wrapper.properties
  bwc-test/gradlew
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: dependencies

#2741 Use updated method to lookup extension by unique id
  src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java
Labels: backport 2.x

#2717 Upgrade spring-core from 5.3.26 to 5.3.27.
  build.gradle
Labels: backport 1.x, backport 1.3, backport 2.x

#2749 Use ExtensionsManager.lookupExtensionSettingsById when verifying extension unique id
  src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java
Labels: backport 2.x

#2729 Add default roles for SQL plugin: PPL and cross-cluster search
  config/roles.yml
Labels: backport 2.x

#2737 [Manual Backport 2.x] Manually backports auth tokens, service accounts, and multi tenancy changes
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/action/tenancy/EmptyRequest.java
  src/main/java/org/opensearch/security/action/tenancy/TenancyConfigRestHandler.java
  src/main/java/org/opensearch/security/action/tenancy/TenancyConfigRetrieveActions.java
  src/main/java/org/opensearch/security/action/tenancy/TenancyConfigRetrieveResponse.java
  src/main/java/org/opensearch/security/action/tenancy/TenancyConfigRetrieveTransportAction.java
  src/main/java/org/opensearch/security/action/tenancy/TenancyConfigUpdateAction.java
  src/main/java/org/opensearch/security/action/tenancy/TenancyConfigUpdateRequest.java
  src/main/java/org/opensearch/security/action/tenancy/TenancyConfigUpdateTransportAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/InternalUsersApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/MultiTenancyConfigApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/SecurityRestApiActions.java
  src/main/java/org/opensearch/security/dlic/rest/validation/MultiTenancyConfigValidator.java
  src/main/java/org/opensearch/security/securityconf/impl/v7/InternalUserV7.java
  src/main/java/org/opensearch/security/support/ConfigConstants.java
  src/main/java/org/opensearch/security/user/UserService.java
  src/main/java/org/opensearch/security/user/UserServiceException.java
  src/test/java/org/opensearch/security/TransportUserInjectorIntegTest.java
  src/test/java/org/opensearch/security/auditlog/integration/TestAuditlogImpl.java
  src/test/java/org/opensearch/security/dlic/rest/api/MultiTenancyConfigApiTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java
  src/test/java/org/opensearch/security/multitenancy/test/TenancyDefaultTenantTests.java
  src/test/java/org/opensearch/security/multitenancy/test/TenancyMultitenancyEnabledTests.java
  src/test/java/org/opensearch/security/multitenancy/test/TenancyPrivateTenantEnabledTests.java
  src/test/resources/multitenancy/internal_users.yml
  src/test/resources/multitenancy/roles.yml
  src/test/resources/multitenancy/roles_mapping.yml
Labels: backport 2.7

#2801 Remove dependency on javax.annotation implementation as OpenSearch now has one.
  build.gradle
Labels: backport 2.x, backport 2.8

#2808 [FEATURE] usage of JWKS with JWT (w/o OpenID connect)
  src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java
  src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/HTTPJwtKeyByOpenIdConnectAuthenticator.java
  src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/JwtVerifier.java
  src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/KeySetRetriever.java
  src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/HTTPJwtKeyByOpenIdConnectAuthenticatorTest.java
  src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/MockIpdServer.java
  src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/SingleKeyHTTPJwtKeyByOpenIdConnectAuthenticatorTest.java
  src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/TestJwts.java
Labels: backport 2.x, backport 2.8
