Repository opensearch-project/security, pull requests merged in 2023-12, with the labels that each got.

#3792 [BUG-3791] Adds missing permissions in logstash static role
  src/main/resources/static_config/static_roles.yml
Labels: backport 2.x

#3824 [Backport 2.x] Resolve logback-classic to 1.2.13
  build.gradle
Labels: backport 1.x, backport 1.3

#3846 [Backport 1.3] Bump Logback Classic to 1.2.13 (resolves CVE-2023-6481)
  build.gradle
Labels: backport 1.x

#3850 Removes support for txt file for specifying initial admin password and prevents password from being printed in the logs
  .github/actions/start-opensearch-with-one-plugin/action.yml
  src/main/java/org/opensearch/security/support/ConfigConstants.java
  src/main/java/org/opensearch/security/tools/democonfig/Installer.java
  src/main/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurer.java
  src/test/java/org/opensearch/security/tools/democonfig/InstallerTests.java
  src/test/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurerTests.java
  src/test/java/org/opensearch/security/tools/democonfig/util/NoExitSecurityManager.java
Labels: v2.12.0

#3851 Add flow framework system indices and roles
  config/roles.yml
  src/main/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurer.java
Labels: backport 2.x

#3845 [2.x] Extracts demo configuration setup into a java tool, adds support for Bundled JDK for this tool and updates DEVELOPER_GUIDE.md
  .github/actions/start-opensearch-with-one-plugin/action.yml
  .github/workflows/plugin_install.yml
  DEVELOPER_GUIDE.md
  README.md
  build.gradle
  scripts/integtest.sh
  src/main/java/org/opensearch/security/support/ConfigConstants.java
  src/main/java/org/opensearch/security/tools/democonfig/CertificateGenerator.java
  src/main/java/org/opensearch/security/tools/democonfig/Certificates.java
  src/main/java/org/opensearch/security/tools/democonfig/ExecutionEnvironment.java
  src/main/java/org/opensearch/security/tools/democonfig/Installer.java
  src/main/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurer.java
  src/test/java/org/opensearch/security/sanity/tests/InvalidAdminPasswordIT.java
  src/test/java/org/opensearch/security/sanity/tests/SingleClusterSanityIT.java
  src/test/java/org/opensearch/security/tools/democonfig/CertificateGeneratorTests.java
  src/test/java/org/opensearch/security/tools/democonfig/InstallerTests.java
  src/test/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurerTests.java
  src/test/java/org/opensearch/security/tools/democonfig/util/DemoConfigHelperUtil.java
  src/test/java/org/opensearch/security/tools/democonfig/util/NoExitSecurityManager.java
  tools/install_demo_configuration.bat
  tools/install_demo_configuration.sh
Labels: v2.12.0

#3689 Add render search template as a cluster permission
  src/integrationTest/java/org/opensearch/security/privileges/PrivilegesEvaluatorTest.java
  src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
Labels: backport 2.x

#3887 Add deprecation check for `jwt_header` setting
  src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java
  src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java
Labels: backport 2.x
