Repository opensearch-project/security, pull requests merged in 2023-02, with the labels that each got.

#2425 Add release note for 1.3.8
  release-notes/opensearch-security.release-notes-1.3.8.0.md
Labels: backport 1.x

#2471 Flatten response times
  src/main/java/org/opensearch/security/auth/internal/InternalAuthenticationBackend.java
  src/test/java/org/opensearch/security/auth/InternalAuthBackendTests.java
Labels: backport 1.x, backport 1.3, backport 2.x

#2459 Support multitenancy for the anonymous user
  src/main/java/org/opensearch/security/auth/BackendRegistry.java
  src/test/java/org/opensearch/security/multitenancy/test/MultitenancyTests.java
  src/test/resources/multitenancy/config_anonymous.yml
  src/test/resources/multitenancy/roles.yml
  src/test/resources/multitenancy/roles_mapping.yml
  src/test/resources/multitenancy/roles_tenants.yml
Labels: backport 2.x
