Repository opensearch-project/security, pull requests merged in 2023-03, with the labels that each got.

#2503 Adding index template permissions to kibana_server role
  src/main/resources/static_config/static_roles.yml
Labels: backport 1.x, backport 1.3, backport 2.x, backport 2.6

#2498 Fix lost privileges during auto initializing of the index
  src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java
  src/main/java/org/opensearch/security/support/ConfigHelper.java
Labels: backport 2.x

#2520 Update to gradle 8.0.2
  build.gradle
  bwc-test/gradle/wrapper/gradle-wrapper.jar
  bwc-test/gradle/wrapper/gradle-wrapper.properties
  bwc-test/gradlew
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: backport 2.x

#2525 Fix error message when system index is blocked
  src/main/java/org/opensearch/security/privileges/SecurityIndexAccessEvaluator.java
  src/test/java/org/opensearch/security/privileges/SecurityIndexAccessEvaluatorTest.java
Labels: backport 2.x

#2539 Add release notes for 1.3.9
  release-notes/opensearch-security.release-notes-1.3.9.0.md
Labels: backport 1.3

#2579 [Backport 1.0] Upgrade CXF and reissue certificates (#1943)
  pom.xml
  src/test/java/org/opensearch/security/ssl/SecuritySSLReloadCertsActionTests.java
  src/test/resources/ssl/reload/kirk-keystore.jks
  src/test/resources/ssl/reload/node-new.crt.pem
  src/test/resources/ssl/reload/node-new.key.pem
  src/test/resources/ssl/reload/node-wrong.crt.pem
  src/test/resources/ssl/reload/node-wrong.key.pem
  src/test/resources/ssl/reload/node.crt.pem
  src/test/resources/ssl/reload/node.key.pem
  src/test/resources/ssl/reload/root-ca.pem
  src/test/resources/ssl/reload/spock-keystore.jks
  src/test/resources/ssl/reload/truststore.jks
Labels: v1.0.0, backport 1.0

#2606 Remediate CVE-2023-1370 and CVE-2023-20861 via version bumps
  build.gradle
Labels: backport 1.x, backport 1.3, backport 2.x, backport 2.6

#2585 Expand Dls Tests for easier verification of functionality
  src/integrationTest/java/org/opensearch/security/DlsIntegrationTests.java
  src/test/java/org/opensearch/security/dlic/dlsfls/DlsTest.java
Labels: backport 1.x, backport 1.3, backport 2.x, backport 2.6
