Repository opensearch-project/security, pull requests merged in 2023-10, with the labels that each got.

#3419 [Enhancement] Setup auth token utils for obo
  src/main/java/org/opensearch/security/authtoken/jwt/JwtVendor.java
  src/main/java/org/opensearch/security/http/OnBehalfOfAuthenticator.java
  src/main/java/org/opensearch/security/securityconf/DynamicConfigModelV7.java
  src/main/java/org/opensearch/security/util/AuthTokenUtils.java
  src/test/java/org/opensearch/security/authtoken/jwt/AuthTokenUtilsTest.java
Labels: backport 2.x, v2.11.0

#3411 Refactors reRequestAuthentication to call notifyIpAuthFailureListener before sending the response to the channel
  src/integrationTest/java/org/opensearch/security/IpBruteForceAttacksPreventionTests.java
  src/integrationTest/java/org/opensearch/security/IpBruteForceAttacksPreventionWithDomainChallengeTests.java
  src/integrationTest/java/org/opensearch/test/framework/cluster/LocalOpenSearchCluster.java
  src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java
  src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java
  src/main/java/com/amazon/dlic/auth/http/kerberos/HTTPSpnegoAuthenticator.java
  src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java
  src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java
  src/main/java/org/opensearch/security/auth/BackendRegistry.java
  src/main/java/org/opensearch/security/auth/HTTPAuthenticator.java
  src/main/java/org/opensearch/security/http/HTTPBasicAuthenticator.java
  src/main/java/org/opensearch/security/http/HTTPClientCertAuthenticator.java
  src/main/java/org/opensearch/security/http/HTTPProxyAuthenticator.java
  src/main/java/org/opensearch/security/http/OnBehalfOfAuthenticator.java
  src/main/java/org/opensearch/security/http/proxy/HTTPExtendedProxyAuthenticator.java
  src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
  src/test/java/org/opensearch/security/auth/limiting/AddressBasedRateLimiterTest.java
  src/test/java/org/opensearch/security/auth/limiting/UserNameBasedRateLimiterTest.java
  src/test/java/org/opensearch/security/cache/DummyHTTPAuthenticator.java
Labels: backport 2.x

#3444 [Backport 2.x] Improve serialization speeds (#2802)
  bwc-test/build.gradle
  bwc-test/src/test/java/SecurityBackwardsCompatibilityIT.java
  bwc-test/src/test/java/org/opensearch/security/bwc/ClusterType.java
  bwc-test/src/test/java/org/opensearch/security/bwc/SecurityBackwardsCompatibilityIT.java
  bwc-test/src/test/java/org/opensearch/security/bwc/Song.java
  bwc-test/src/test/java/org/opensearch/security/bwc/helper/RestHelper.java
  src/main/java/com/amazon/dlic/auth/ldap/LdapUser.java
  src/main/java/org/opensearch/security/auditlog/impl/AbstractAuditLog.java
  src/main/java/org/opensearch/security/auth/UserInjector.java
  src/main/java/org/opensearch/security/configuration/DlsFlsValveImpl.java
  src/main/java/org/opensearch/security/filter/SecurityFilter.java
  src/main/java/org/opensearch/security/ssl/transport/SecuritySSLRequestHandler.java
  src/main/java/org/opensearch/security/support/Base64CustomHelper.java
  src/main/java/org/opensearch/security/support/Base64Helper.java
  src/main/java/org/opensearch/security/support/Base64JDKHelper.java
  src/main/java/org/opensearch/security/support/ConfigConstants.java
  src/main/java/org/opensearch/security/support/HeaderHelper.java
  src/main/java/org/opensearch/security/support/SafeSerializationUtils.java
  src/main/java/org/opensearch/security/support/SourceFieldsContext.java
  src/main/java/org/opensearch/security/support/StreamableRegistry.java
  src/main/java/org/opensearch/security/transport/SecurityInterceptor.java
  src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java
  src/main/java/org/opensearch/security/user/User.java
  src/test/java/org/opensearch/security/support/Base64CustomHelperTest.java
  src/test/java/org/opensearch/security/support/Base64HelperTest.java
  src/test/java/org/opensearch/security/support/Base64JDKHelperTest.java
  src/test/java/org/opensearch/security/support/StreamableRegistryTest.java
  src/test/java/org/opensearch/security/transport/SecurityInterceptorTests.java
  src/test/java/org/opensearch/security/transport/SecuritySSLRequestHandlerTests.java
Labels: v2.11.0

#3445 [Backport 2.x] Refactors reRequestAuthentication to call notifyIpAuthFailureListener before sending the response to the channel (#3411)
  src/integrationTest/java/org/opensearch/security/IpBruteForceAttacksPreventionTests.java
  src/integrationTest/java/org/opensearch/security/IpBruteForceAttacksPreventionWithDomainChallengeTests.java
  src/integrationTest/java/org/opensearch/test/framework/cluster/LocalOpenSearchCluster.java
  src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java
  src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java
  src/main/java/com/amazon/dlic/auth/http/kerberos/HTTPSpnegoAuthenticator.java
  src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java
  src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java
  src/main/java/org/opensearch/security/auth/BackendRegistry.java
  src/main/java/org/opensearch/security/auth/HTTPAuthenticator.java
  src/main/java/org/opensearch/security/http/HTTPBasicAuthenticator.java
  src/main/java/org/opensearch/security/http/HTTPClientCertAuthenticator.java
  src/main/java/org/opensearch/security/http/HTTPProxyAuthenticator.java
  src/main/java/org/opensearch/security/http/proxy/HTTPExtendedProxyAuthenticator.java
  src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
  src/test/java/org/opensearch/security/auth/limiting/AddressBasedRateLimiterTest.java
  src/test/java/org/opensearch/security/auth/limiting/UserNameBasedRateLimiterTest.java
  src/test/java/org/opensearch/security/cache/DummyHTTPAuthenticator.java
Labels: v2.11.0

#2956 [Backport 2.x] Authorize rest requests (#2753) and Enhance RestLayerPrivilegesEvaluator Code Coverage (#3218)
  DEVELOPER_GUIDE.md
  REST_AUTHZ_FOR_PLUGINS.md
  src/integrationTest/java/org/opensearch/security/rest/WhoAmITests.java
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/auditlog/impl/AbstractAuditLog.java
  src/main/java/org/opensearch/security/dlic/rest/support/Utils.java
  src/main/java/org/opensearch/security/filter/SecurityRestFilter.java
  src/main/java/org/opensearch/security/privileges/RestLayerPrivilegesEvaluator.java
  src/main/java/org/opensearch/security/rest/SecurityWhoAmIAction.java
  src/test/java/org/opensearch/security/SystemIntegratorsTests.java
  src/test/java/org/opensearch/security/filter/RestPathMatchesTests.java
  src/test/java/org/opensearch/security/filter/SecurityFilterTests.java
  src/test/java/org/opensearch/security/filter/SecurityRestFilterTests.java
  src/test/java/org/opensearch/security/privileges/RestLayerPrivilegesEvaluatorTest.java
  src/test/resources/roles.yml
  src/test/resources/roles_mapping.yml
Labels: v2.11.0

#3264 Support security config updates on the REST API using permission
  config/roles.yml
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/dlic/rest/api/RestApiAdminPrivilegesEvaluator.java
  src/main/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/SecurityRestApiActions.java
  src/main/java/org/opensearch/security/dlic/rest/api/SecuritySSLCertsApiAction.java
  src/test/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiActionTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiActionValidationTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/SecuritySSLCertsApiActionValidationTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java
  src/test/java/org/opensearch/security/securityconf/SecurityRolesPermissionsTest.java
  src/test/resources/restapi/internal_users.yml
  src/test/resources/restapi/roles.yml
  src/test/resources/restapi/roles_mapping.yml
Labels: backport 2.x

#3458 [Build Break] Update custom serialization min supported version
  src/main/java/org/opensearch/security/support/ConfigConstants.java
  src/test/java/org/opensearch/security/transport/SecuritySSLRequestHandlerTests.java
Labels: Priority-High, backwards-compatibility

#3454 Redirect deprecation messages to stderr.
  tools/hash.sh
Labels: backport 2.x

#3459 [Backport 2.x] Support security config updates on the REST API using permission (#3264)
  config/roles.yml
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/dlic/rest/api/RestApiAdminPrivilegesEvaluator.java
  src/main/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/SecurityRestApiActions.java
  src/main/java/org/opensearch/security/dlic/rest/api/SecuritySSLCertsApiAction.java
  src/test/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiActionTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiActionValidationTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/SecuritySSLCertsApiActionValidationTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java
  src/test/java/org/opensearch/security/securityconf/SecurityRolesPermissionsTest.java
  src/test/resources/restapi/internal_users.yml
  src/test/resources/restapi/roles.yml
  src/test/resources/restapi/roles_mapping.yml
Labels: v2.11.0

#3463 Add tracer to Transport
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/ssl/OpenSearchSecuritySSLPlugin.java
  src/main/java/org/opensearch/security/ssl/transport/SecuritySSLNettyTransport.java
Labels: backport 2.x, backport 2.11

#3474 Adds opensearch trigger bot to discerning merger list to allow automatic merges
  .github/workflows/automatic-merges.yml
Labels: backport 1.x, backport 1.3, backport 2.x, backport 2.11

#3479 [Backport 2.x] Add missing license header (#3467)
  src/test/java/org/opensearch/security/transport/SecuritySSLRequestHandlerTests.java
Labels: v2.11.0

#3457 Get OpenSearch version from gradle properties
  DEVELOPER_GUIDE.md
Labels: backport 1.x, backport 2.x

#3453 Adds 2.11.0.0 release notes
  release-notes/opensearch-security.release-notes-2.11.0.0.md
Labels: backport 2.x, backport 2.11

#3532 Bump org.apache.zookeeper:zookeeper to 3.9.1 and io.netty:netty-tcnative-boringssl-static to 2.0.61.Final
  build.gradle
Labels: backport 2.x

#3358 [Improvement] Enable warnings during compilation
  build.gradle
  src/integrationTest/java/org/opensearch/node/PluginAwareNode.java
  src/integrationTest/java/org/opensearch/test/framework/cluster/ClusterManager.java
  src/integrationTest/java/org/opensearch/test/framework/cluster/LocalOpenSearchCluster.java
  src/main/java/org/opensearch/security/DefaultObjectMapper.java
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/auditlog/impl/AbstractAuditLog.java
  src/main/java/org/opensearch/security/auditlog/impl/RequestResolver.java
  src/main/java/org/opensearch/security/auditlog/routing/AuditMessageRouter.java
  src/main/java/org/opensearch/security/auditlog/sink/InternalOpenSearchSink.java
  src/main/java/org/opensearch/security/auth/BackendRegistry.java
  src/main/java/org/opensearch/security/auth/UserInjector.java
  src/main/java/org/opensearch/security/configuration/DlsFlsValveImpl.java
  src/main/java/org/opensearch/security/dlic/rest/api/InternalUsersApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/MigrateApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/validation/RequestContentValidator.java
  src/main/java/org/opensearch/security/http/HTTPProxyAuthenticator.java
  src/main/java/org/opensearch/security/http/XFFResolver.java
  src/main/java/org/opensearch/security/securityconf/ConfigModelV6.java
  src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java
  src/main/java/org/opensearch/security/securityconf/DynamicConfigFactory.java
  src/main/java/org/opensearch/security/securityconf/Migration.java
  src/main/java/org/opensearch/security/securityconf/impl/SecurityDynamicConfiguration.java
  src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java
  src/main/java/org/opensearch/security/ssl/transport/SecuritySSLRequestHandler.java
  src/main/java/org/opensearch/security/ssl/util/Utils.java
  src/main/java/org/opensearch/security/support/SecurityUtils.java
  src/main/java/org/opensearch/security/support/WildcardMatcher.java
  src/main/java/org/opensearch/security/user/UserService.java
  src/test/java/com/amazon/dlic/auth/ldap/LdapBackendTest.java
  src/test/java/com/amazon/dlic/auth/ldap/LdapBackendTestNewStyleConfig.java
  src/test/java/com/amazon/dlic/auth/ldap2/LdapBackendTestNewStyleConfig2.java
  src/test/java/com/amazon/dlic/auth/ldap2/LdapBackendTestOldStyleConfig2.java
  src/test/java/org/opensearch/node/PluginAwareNode.java
  src/test/java/org/opensearch/security/ConfigTests.java
  src/test/java/org/opensearch/security/InitializationIntegrationTests.java
  src/test/java/org/opensearch/security/RolesInjectorIntegTest.java
  src/test/java/org/opensearch/security/RolesValidationIntegTest.java
  src/test/java/org/opensearch/security/SlowIntegrationTests.java
  src/test/java/org/opensearch/security/TransportUserInjectorIntegTest.java
  src/test/java/org/opensearch/security/UtilTests.java
  src/test/java/org/opensearch/security/auth/UserInjectorTest.java
  src/test/java/org/opensearch/security/ccstest/CrossClusterSearchTests.java
  src/test/java/org/opensearch/security/dlic/dlsfls/CCReplicationTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/AbstractRestApiUnitTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/RolesApiTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java
  src/test/java/org/opensearch/security/multitenancy/test/MultitenancyTests.java
  src/test/java/org/opensearch/security/ssl/OpenSSLTest.java
  src/test/java/org/opensearch/security/ssl/SSLTest.java
  src/test/java/org/opensearch/security/support/Base64HelperTest.java
  src/test/java/org/opensearch/security/support/Base64JDKHelperTest.java
  src/test/java/org/opensearch/security/test/helper/cluster/ClusterConfiguration.java
  src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java
  src/test/java/org/opensearch/security/transport/SecurityInterceptorTests.java
Labels: backport 2.x

#3517 Use DelegatingRestHandler to delegate to the original handler
  src/main/java/org/opensearch/security/filter/DelegatingRestHandler.java
  src/main/java/org/opensearch/security/filter/SecurityRestFilter.java
  src/test/java/org/opensearch/security/filter/DelegatingRestHandlerTests.java
  src/test/java/org/opensearch/security/filter/SecurityRestFilterUnitTests.java
Labels: backport 2.x

#3506 [Cleanup] Remove duplication in Netty4HttpRequestHeaderVerifier
  src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java
  src/main/java/org/opensearch/security/filter/SecurityRequest.java
  src/main/java/org/opensearch/security/filter/SecurityRequestChannelUnsupported.java
  src/main/java/org/opensearch/security/filter/SecurityRestFilter.java
  src/main/java/org/opensearch/security/filter/SecurityRestUtils.java
  src/main/java/org/opensearch/security/ssl/http/netty/Netty4HttpRequestHeaderVerifier.java
  src/test/java/org/opensearch/security/filter/SecurityRestUtilsTests.java
Labels: backport 2.x

#3548 Removes prefix from dependabot's commit message
  .github/dependabot.yml
Labels: backport 1.x, backport 1.3, backport 2.x

#3576 Bump peternied/discerning-merger from 2 to 3
  .github/workflows/automatic-merges.yml
Labels: backport 2.x

#3563 [Backport 2.x] Feature OnBehalfOf Authentication
  src/integrationTest/java/org/opensearch/security/http/OnBehalfOfJwtAuthenticationTest.java
  src/integrationTest/java/org/opensearch/test/framework/TestSecurityConfig.java
  src/integrationTest/java/org/opensearch/test/framework/cluster/LocalCluster.java
  src/integrationTest/resources/config.yml
  src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/action/onbehalf/CreateOnBehalfOfTokenAction.java
  src/main/java/org/opensearch/security/auth/BackendRegistry.java
  src/main/java/org/opensearch/security/auth/HTTPAuthenticator.java
  src/main/java/org/opensearch/security/auth/internal/NoOpAuthenticationBackend.java
  src/main/java/org/opensearch/security/authtoken/jwt/EncryptionDecryptionUtil.java
  src/main/java/org/opensearch/security/authtoken/jwt/JwtVendor.java
  src/main/java/org/opensearch/security/configuration/ClusterInfoHolder.java
  src/main/java/org/opensearch/security/http/OnBehalfOfAuthenticator.java
  src/main/java/org/opensearch/security/securityconf/DynamicConfigFactory.java
  src/main/java/org/opensearch/security/securityconf/DynamicConfigModel.java
  src/main/java/org/opensearch/security/securityconf/DynamicConfigModelV6.java
  src/main/java/org/opensearch/security/securityconf/DynamicConfigModelV7.java
  src/main/java/org/opensearch/security/securityconf/impl/v6/ConfigV6.java
  src/main/java/org/opensearch/security/securityconf/impl/v7/ConfigV7.java
  src/main/java/org/opensearch/security/ssl/util/ExceptionUtils.java
  src/main/java/org/opensearch/security/user/AuthCredentials.java
  src/main/java/org/opensearch/security/util/AuthTokenUtils.java
  src/main/java/org/opensearch/security/util/KeyUtils.java
  src/test/java/org/opensearch/security/authtoken/jwt/AuthTokenUtilsTest.java
  src/test/java/org/opensearch/security/authtoken/jwt/EncryptionDecryptionUtilsTest.java
  src/test/java/org/opensearch/security/authtoken/jwt/JwtVendorTest.java
  src/test/java/org/opensearch/security/http/OnBehalfOfAuthenticatorTest.java
  src/test/resources/restapi/securityconfig_nondefault.json
Labels: v2.12.0

#3421 Switch JWT library implementations from cxf to nimbus
  build.gradle
  checkstyle/checkstyle.xml
  src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java
  src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/JwtVerifier.java
  src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/KeyProvider.java
  src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/KeySetProvider.java
  src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/KeySetRetriever.java
  src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/SelfRefreshingKeySet.java
  src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java
  src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java
  src/main/java/org/opensearch/security/authtoken/jwt/JwtVendor.java
  src/main/java/org/opensearch/security/authtoken/jwt/KeyPaddingUtil.java
  src/test/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticatorTest.java
  src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/HTTPJwtKeyByOpenIdConnectAuthenticatorTest.java
  src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/MockIpdServer.java
  src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/SelfRefreshingKeySetTest.java
  src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/SingleKeyHTTPJwtKeyByOpenIdConnectAuthenticatorTest.java
  src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/TestJwk.java
  src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/TestJwts.java
  src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
  src/test/java/org/opensearch/security/authtoken/jwt/JwtVendorTest.java
  src/test/java/org/opensearch/security/authtoken/jwt/KeyPaddingUtilTest.java
Labels: backport 2.x, v2.12.0

#3583 Use new instance of Decompressor on channel initialization
  src/integrationTest/java/org/opensearch/security/ResourceFocusedTests.java
  src/integrationTest/java/org/opensearch/security/rest/CompressionTests.java
  src/main/java/org/opensearch/security/http/SecurityNonSslHttpServerTransport.java
  src/main/java/org/opensearch/security/ssl/http/netty/Netty4ConditionalDecompressor.java
  src/main/java/org/opensearch/security/ssl/http/netty/SecuritySSLNettyHttpServerTransport.java
Labels: backport 2.x, backport 2.11

#3594 Wraps HTTPJwtAuthenticator jwtParserBuilder.build call with access controller to prevent AccessControlException
  src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java
Labels: backport 2.x

#3593 OnBehalfOf tokens odds and ends
  src/integrationTest/java/org/opensearch/security/DefaultConfigurationTests.java
  src/integrationTest/java/org/opensearch/security/SecurityConfigurationTests.java
  src/integrationTest/java/org/opensearch/security/http/CertificateAuthenticationTest.java
  src/integrationTest/java/org/opensearch/security/http/OnBehalfOfJwtAuthenticationTest.java
  src/integrationTest/java/org/opensearch/test/framework/cluster/TestRestClient.java
  src/main/java/org/opensearch/security/action/onbehalf/CreateOnBehalfOfTokenAction.java
  src/main/java/org/opensearch/security/authtoken/jwt/JwtVendor.java
  src/test/java/org/opensearch/security/authtoken/jwt/JwtVendorTest.java
Labels: backport 2.x

#3605 Remove unneeded decoding from AuthTokenProcessorHandler
  src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java
  src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
Labels: backport 2.x

#3554 Re-enables CrossClusterSearchTests
  src/integrationTest/java/org/opensearch/security/CrossClusterSearchTests.java
Labels: backport 2.x

#3536 Bump jjwt_version from 0.11.5 to 0.12.3
  build.gradle
  src/integrationTest/java/org/opensearch/security/http/OnBehalfOfJwtAuthenticationTest.java
  src/main/java/org/opensearch/security/http/OnBehalfOfAuthenticator.java
  src/main/java/org/opensearch/security/util/KeyUtils.java
  src/test/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticatorTest.java
  src/test/java/org/opensearch/security/http/OnBehalfOfAuthenticatorTest.java
Labels: backport 2.x

#3621 Change log message with jwtString from INFO to TRACE
  src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java
Labels: backport 2.x

#3607 Limit service account permission
  src/integrationTest/java/org/opensearch/security/http/ServiceAccountAuthenticationTest.java
  src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
  src/main/java/org/opensearch/security/privileges/SecurityIndexAccessEvaluator.java
  src/main/java/org/opensearch/security/user/User.java
  src/test/java/org/opensearch/security/IntegrationTests.java
  src/test/java/org/opensearch/security/UserServiceUnitTests.java
  src/test/resources/internal_users.yml
Labels: backport 2.x, v2.12.0
