Repository opensearch-project/security, pull requests merged in 2023-07, with the labels that each got.

#2919 [Backport 1.x] Bump BouncyCastle from jdk15on to jdk15to18 (#2901)
  build.gradle
  plugin-security.policy
  src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java
Labels: backport 1.3

#2947 Add .plugins-ml-connector to system index
  tools/install_demo_configuration.bat
  tools/install_demo_configuration.sh
Labels: backport 2.x

#2949 Add password message to /dashboardsinfo endpoint
  src/integrationTest/java/org/opensearch/security/api/DashboardsInfoTest.java
  src/integrationTest/java/org/opensearch/security/api/DashboardsInfoWithSettingsTest.java
  src/main/java/org/opensearch/security/rest/DashboardsInfoAction.java
Labels: backport 2.x

#2927 Bump SAML libs
  build.gradle
  src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java
  src/main/java/com/amazon/dlic/auth/http/saml/Saml2SettingsProvider.java
  src/main/java/com/amazon/dlic/auth/http/saml/SamlHTTPMetadataResolver.java
  src/test/java/com/amazon/dlic/auth/http/saml/MockSamlIdpServer.java
Labels: backport 2.x

#2924 Remove commons-collections 3.2.2
  build.gradle
  src/integrationTest/java/org/opensearch/test/framework/log/LogCapturingAppender.java
  src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java
Labels: backport 2.x

#2753 Authorize rest requests
  DEVELOPER_GUIDE.md
  REST_AUTHZ_FOR_PLUGINS.md
  src/integrationTest/java/org/opensearch/security/rest/WhoAmITests.java
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/auditlog/impl/AbstractAuditLog.java
  src/main/java/org/opensearch/security/dlic/rest/support/Utils.java
  src/main/java/org/opensearch/security/filter/SecurityRestFilter.java
  src/main/java/org/opensearch/security/privileges/RestLayerPrivilegesEvaluator.java
  src/main/java/org/opensearch/security/rest/SecurityWhoAmIAction.java
  src/test/java/org/opensearch/security/SystemIntegratorsTests.java
  src/test/java/org/opensearch/security/filter/RestPathMatchesTest.java
  src/test/java/org/opensearch/security/privileges/RestLayerPrivilegesEvaluatorTest.java
  src/test/resources/roles.yml
  src/test/resources/roles_mapping.yml
Labels: backport 2.x, v2.9.0

#2765 Adds a check to skip serialization-deserialization if request is for same node
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/transport/SecurityInterceptor.java
  src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java
  src/test/java/org/opensearch/security/transport/SecurityInterceptorTests.java
Labels: backport 2.x, v2.9.0

#2965 Bump eventbus to 3.3.1
  build.gradle
Labels: backport 2.x

#2974 [Backport 2.x] Resolve CVE-2023-2976 by forcing use of Guava 32.0.1 (#2937)
  build.gradle
Labels: v2.9.0

#2977 Bump org.glassfish.jaxb:jaxb-runtime and org.glassfish.jaxb:txw2 to 2.3.8
  build.gradle
Labels: backport 2.x

#2978 Update Gradle to 8.2.1
  bwc-test/gradle/wrapper/gradle-wrapper.jar
  bwc-test/gradle/wrapper/gradle-wrapper.properties
  bwc-test/gradlew
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: backport 2.x

#2995 [2.x] Use version of log4j from core's buildSrc/version.properties
  build.gradle
Labels: backport 2.9

#3018 [2.9] Updates common-utils version in integ test script
  scripts/integtest.sh
Labels: v2.9.0

#2992 Add release notes for 2.9.0.0
  release-notes/opensearch-security.release-notes-2.9.0.0.md
Labels: backport 2.x

#2993 add .plugins-ml-config in the system index
  tools/install_demo_configuration.bat
  tools/install_demo_configuration.sh
Labels: backport 2.x

#3023 Update ospackage, checker-qual, zcxvbn and error_prone_annotations, camel-xmlsecurity
  build.gradle
Labels: backport 2.x

#2994 add workflow cluster permissions to alerting roles
  config/roles.yml
Labels: backport 2.x

#3050 Adapt MediaType library change in core
  src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java
  src/main/java/org/opensearch/security/auditlog/impl/AbstractAuditLog.java
  src/main/java/org/opensearch/security/auditlog/impl/AuditMessage.java
  src/main/java/org/opensearch/security/auditlog/impl/RequestResolver.java
  src/main/java/org/opensearch/security/dlic/rest/api/PatchableResourceApiAction.java
  src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
Labels: v2.10.0

#3037 [Backport 2.x] Added secure settings for ssl related passwords: (#2296)
  src/main/java/com/amazon/dlic/auth/ldap/backend/LDAPAuthorizationBackend.java
  src/main/java/com/amazon/dlic/util/SettingsBasedSSLConfigurator.java
  src/main/java/org/opensearch/security/auditlog/sink/ExternalOpenSearchSink.java
  src/main/java/org/opensearch/security/auditlog/sink/WebhookSink.java
  src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java
  src/main/java/org/opensearch/security/ssl/OpenSearchSecuritySSLPlugin.java
  src/main/java/org/opensearch/security/ssl/SecureSSLSettings.java
  src/main/java/org/opensearch/security/ssl/util/SSLConfigConstants.java
  src/main/java/org/opensearch/security/ssl/util/SSLRequestHelper.java
  src/test/java/org/opensearch/security/sanity/tests/SecurityRestTestCase.java
  src/test/java/org/opensearch/security/ssl/SSLTest.java
  src/test/java/org/opensearch/security/ssl/SecureSSLSettingsTest.java
Labels: v2.10.0

#3066 Remove static local-node reference
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/transport/SecurityInterceptor.java
  src/test/java/org/opensearch/security/transport/SecurityInterceptorTests.java
Labels: backport 2.x

#3062 bump com.github.wnameless.json:json-base from 2.4.0 to 2.4.1
  build.gradle
Labels: backport 2.x
