Repository opensearch-project/security, pull requests merged in 2023-01, with the labels that each got.

#2375 When excluding fields also exclude the term + `.keyword`
  src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java
  src/test/java/org/opensearch/security/dlic/dlsfls/FlsKeywordTests.java
  src/test/resources/dlsfls/roles_keyword.yml
  src/test/resources/dlsfls/roles_mappings_keyword.yml
Labels: backport 2.x, v2.5.0

#2371 Update tool scripts to run in windows
  tools/audit_config_migrater.bat
  tools/hash.bat
  tools/securityadmin.bat
Labels: windows, backport 1.x, backport 2.x

#2381 Remove trimming of whitespace when extracting SAML backend roles
  src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java
  src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
Labels: backport 2.x

#2374 Add script for workflow version increment
  build.gradle
Labels: backport 2.x, backport 2.4

#2391 Re-add jackson-annotations and jackson-databind
  build.gradle
Labels: backport 2.x, backport 2.5

#2394 Add release note for 2.5.0
  release-notes/opensearch-security.release-notes-2.5.0.0.md
Labels: backport 2.x, backport 2.5

#2388 [Backport 1.X] Update tool scripts to run in windows (#2371)
  tools/audit_config_migrater.bat
  tools/hash.bat
  tools/securityadmin.bat
Labels: backport 1.3

#2401 Revert "Windows Install Action Fix"
  .github/workflows/plugin_install.yml
  tools/install_demo_configuration.bat
  tools/install_demo_configuration.sh
Labels: backport 1.3, backport 2.x, backport 2.4, backport 2.5

#2409 Add action indices:admin/index_template/* to cluster_manage_index_tem…
  src/main/resources/static_config/static_action_groups.yml
Labels: backport 2.x
