Repository opensearch-project/security, pull requests merged in 2023-04, with the labels that each got.

#2670 Gradle plugin updates (spotless, ospackage)
  build.gradle
Labels: dependencies, backport 2.x

#2679 Update certs for SecuritySSLReloadCertsActionTests
  src/test/java/org/opensearch/security/ssl/SecuritySSLReloadCertsActionTests.java
  src/test/resources/ssl/reload/kirk-keystore.jks
  src/test/resources/ssl/reload/node-new.crt.pem
  src/test/resources/ssl/reload/node-new.key.pem
  src/test/resources/ssl/reload/node-wrong.crt.pem
  src/test/resources/ssl/reload/node-wrong.key.pem
  src/test/resources/ssl/reload/node.crt.pem
  src/test/resources/ssl/reload/node.key.pem
  src/test/resources/ssl/reload/root-ca.pem
  src/test/resources/ssl/reload/spock-keystore.jks
  src/test/resources/ssl/reload/truststore.jks
Labels: backport 1.x, backport 1.3, backport 2.x

#2690 Add release notes for 2.7.0
  release-notes/opensearch-security.release-notes-2.6.0.0.md
  release-notes/opensearch-security.release-notes-2.7.0.0.md
Labels: backport 2.x, backport 2.7

#2691 [Backport 1.x] Fix NPE and add additional graceful error handling
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/support/GuardedSearchOperationWrapper.java
  src/test/java/org/opensearch/security/support/GuardedSearchOperationWrapperTest.java
Labels: backport 1.3

#2711 Corrects CVE-2023-20863 by forcing spring-expression version
  build.gradle
Labels: backport 1.x
