Repository opensearch-project/security, pull requests merged in 2023-06, with the labels that each got.

#2827 Add release notes for 2.8.0
  release-notes/opensearch-security.release-notes-2.8.0.0.md
Labels: backport 2.x

#2832 Match version of zstd-jni from core
  build.gradle
Labels: backport 2.x

#2855 add search model group permission to ml_read_access role
  config/roles.yml
Labels: backport 2.x

#2870 Bumping spring-core and spring-expression from 5.3.26 to 5.3.28 to patch CVE vulnerabilities
  build.gradle
Labels: backport 1.3

#2873 [Backport 1.3] Bumping spring-core from 5.3.26 to 5.3.27 to patch CVE vulnerabilities
  build.gradle
Labels: v1.3.11

#2864 Use boucycastle PEM reader instead of reg expression
  src/main/java/org/opensearch/security/support/PemKeyReader.java
  src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
Labels: backport 2.x

#2876 Adding field level security test cases for FlatFields
  src/test/java/org/opensearch/security/dlic/dlsfls/FlsFlatTests.java
  src/test/resources/dlsfls/roles_fls_flat.yml
Labels: backport 2.x, backport 2.7, backport 2.8

#2886 Update snappy to 1.1.10.1 and guava to 32.0.1-jre
  build.gradle
Labels: backport 2.x

#2893 [Backport 2.x] Adding field level security test cases for FlatFields (#2876)
  src/test/java/org/opensearch/security/dlic/dlsfls/FlsFlatTests.java
  src/test/resources/dlsfls/roles_fls_flat.yml
Labels: backport 2.7, backport 2.8

#2892 fix cluster perm classification for msearch template
  src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
  src/test/java/org/opensearch/security/privileges/PrivilegesEvaluatorUnitTest.java
Labels: backport 2.x

#2901 Bump BouncyCastle from jdk15on to jdk15to18
  build.gradle
  plugin-security.policy
  src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java
Labels: backport 2.x
