Repository opensearch-project/security, pull requests merged in 2023-09, with the labels that each got.

#3283 Fix checkstyle
  build.gradle
  checkstyle/checkstyle.xml
  checkstyle/println_checks.xml
  src/main/java/org/opensearch/security/util/KeyUtils.java
  src/test/java/org/opensearch/security/authtoken/jwt/JwtVendorTest.java
  src/test/java/org/opensearch/security/privileges/PrivilegesEvaluatorUnitTest.java
Labels: backport 2.x

#3306 Use version of org.apache.commons:commons-lang3 defined in core
  build.gradle
Labels: backport 2.x

#3289 Fix permissions issues while reading keys in PKCS#1 format
  plugin-security.policy
  src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java
Labels: backport 2.x

#3326 add conversation system indices for conversation memory experimental …
  tools/install_demo_configuration.bat
  tools/install_demo_configuration.sh
Labels: backport 2.x

#3360 Add release notes for 2.10.0.0
  release-notes/opensearch-security.release-notes-2.10.0.0.md
Labels: backport 2.x

#3383 removing opendistro-job-scheduler-lock from list of protected indices
  tools/install_demo_configuration.bat
  tools/install_demo_configuration.sh
Labels: backport 2.x

#3359 [Refactor] Change HTTP routes for Audit and Config PUT methods
  src/main/java/org/opensearch/security/dlic/rest/api/AbstractApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/AuditApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiAction.java
  src/test/java/org/opensearch/security/dlic/rest/api/AuditApiActionValidationTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiActionTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiActionValidationTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/legacy/LegacySecurityConfigApiActionTests.java
Labels: backport 2.x

#3329 Demo configuration script requires admin password
  .github/actions/start-opensearch-with-one-plugin/action.yml
  .github/workflows/plugin_install.yml
  tools/install_demo_configuration.bat
  tools/install_demo_configuration.sh
Labels: backport 2.x, v2.11.0

#2802 Improve serialization speeds
  .github/workflows/ci.yml
  bwc-test/build.gradle
  bwc-test/src/test/java/SecurityBackwardsCompatibilityIT.java
  bwc-test/src/test/java/org/opensearch/security/bwc/ClusterType.java
  bwc-test/src/test/java/org/opensearch/security/bwc/SecurityBackwardsCompatibilityIT.java
  bwc-test/src/test/java/org/opensearch/security/bwc/Song.java
  bwc-test/src/test/java/org/opensearch/security/bwc/helper/RestHelper.java
  src/main/java/com/amazon/dlic/auth/ldap/LdapUser.java
  src/main/java/org/opensearch/security/auditlog/impl/AbstractAuditLog.java
  src/main/java/org/opensearch/security/auth/UserInjector.java
  src/main/java/org/opensearch/security/configuration/DlsFlsValveImpl.java
  src/main/java/org/opensearch/security/filter/SecurityFilter.java
  src/main/java/org/opensearch/security/ssl/transport/SecuritySSLRequestHandler.java
  src/main/java/org/opensearch/security/support/Base64CustomHelper.java
  src/main/java/org/opensearch/security/support/Base64Helper.java
  src/main/java/org/opensearch/security/support/Base64JDKHelper.java
  src/main/java/org/opensearch/security/support/ConfigConstants.java
  src/main/java/org/opensearch/security/support/HeaderHelper.java
  src/main/java/org/opensearch/security/support/SafeSerializationUtils.java
  src/main/java/org/opensearch/security/support/SourceFieldsContext.java
  src/main/java/org/opensearch/security/support/StreamableRegistry.java
  src/main/java/org/opensearch/security/transport/SecurityInterceptor.java
  src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java
  src/main/java/org/opensearch/security/user/User.java
  src/test/java/org/opensearch/security/support/Base64CustomHelperTest.java
  src/test/java/org/opensearch/security/support/Base64HelperTest.java
  src/test/java/org/opensearch/security/support/Base64JDKHelperTest.java
  src/test/java/org/opensearch/security/support/StreamableRegistryTest.java
  src/test/java/org/opensearch/security/transport/SecurityInterceptorTests.java
  src/test/java/org/opensearch/security/transport/SecuritySSLRequestHandlerTests.java
Labels: v2.11.0
