Repository opensearch-project/security, pull requests merged in 2024-07, with the labels that each got.

#4481 Refactor InternalUsers REST API test
  src/integrationTest/java/org/opensearch/security/api/AbstractApiIntegrationTest.java
  src/integrationTest/java/org/opensearch/security/api/AbstractConfigEntityApiIntegrationTest.java
  src/integrationTest/java/org/opensearch/security/api/InternalUsersRegExpPasswordRulesRestApiIntegrationTest.java
  src/integrationTest/java/org/opensearch/security/api/InternalUsersRestApiIntegrationTest.java
  src/integrationTest/java/org/opensearch/security/api/InternalUsersScoreBasedPasswordRulesRestApiIntegrationTest.java
  src/main/java/org/opensearch/security/dlic/rest/api/InternalUsersApiAction.java
  src/main/java/org/opensearch/security/user/UserService.java
  src/test/java/org/opensearch/security/UserServiceUnitTests.java
  src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/legacy/LegacyUserApiTests.java
Labels: backport 2.x

#4526 [BUG] Typo in securityadmin.sh hint
  src/main/java/org/opensearch/security/tools/SecurityAdmin.java
Labels: backport 2.x

#4530 Update PATCH API to fail validation if nothing changes
  src/integrationTest/java/org/opensearch/security/api/AbstractApiIntegrationTest.java
  src/integrationTest/java/org/opensearch/security/api/ConfigRestApiIntegrationTest.java
  src/integrationTest/java/org/opensearch/security/api/RolesMappingRestApiIntegrationTest.java
  src/integrationTest/java/org/opensearch/security/api/RolesRestApiIntegrationTest.java
  src/main/java/org/opensearch/security/dlic/rest/api/AbstractApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/validation/RequestContentValidator.java
  src/test/java/org/opensearch/security/dlic/rest/api/AuditApiActionTest.java
Labels: backport 2.x

#4490 Separated DLS/FLS privilege evaluation from action privilege evaluation
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/configuration/DlsFilterLevelActionHandler.java
  src/main/java/org/opensearch/security/configuration/DlsFlsRequestValve.java
  src/main/java/org/opensearch/security/configuration/DlsFlsValveImpl.java
  src/main/java/org/opensearch/security/filter/SecurityFilter.java
  src/main/java/org/opensearch/security/privileges/PrivilegesEvaluationContext.java
  src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
  src/main/java/org/opensearch/security/privileges/PrivilegesEvaluatorResponse.java
Labels: backport 2.x

#4541 Add release notes for 1.3.18 release
  release-notes/opensearch-security.release-notes-1.3.18.0.md
Labels: backport 1.x, backport 1.3

#4548 Fixed test failures in FlsAndFieldMaskingTests
  src/integrationTest/java/org/opensearch/security/FlsAndFieldMaskingTests.java
Labels: backport 2.x

#4471 Use SystemIndexRegistry from core to determine if request contains system indices
  src/integrationTest/java/org/opensearch/security/SystemIndexTests.java
  src/integrationTest/java/org/opensearch/security/http/ExampleSystemIndexPlugin.java
  src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
  src/main/java/org/opensearch/security/privileges/SystemIndexAccessEvaluator.java
  src/test/java/org/opensearch/security/privileges/SystemIndexAccessEvaluatorTest.java
Labels: backport 2.x

#4553 Update Gradle to 8.9
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: backport 2.x

#4555 Update the release notes for 1.3.18
  release-notes/opensearch-security.release-notes-1.3.18.0.md
Labels: backport 1.x, backport 1.3

#4558 [Chore] Remove unnecessary return statements
  src/main/java/org/opensearch/security/filter/SecurityRestFilter.java
Labels: backport 2.x

#4569 Pass set to SystemIndexRegistry.matchesSystemIndexPattern
  src/main/java/org/opensearch/security/privileges/SystemIndexAccessEvaluator.java
Labels: backport 2.x

#4579 [1.3] Bump org.apache.cxf:cxf-rt-rs-security-jose from 3.5.8 to 3.5.9
  build.gradle
Labels: backport 1.x

#4596 Adds 2.16 release notes
  release-notes/opensearch-security.release-notes-2.16.0.0.md
Labels: backport 2.x, backport 2.16

#4600 Addresses a bug with `plugins.security.allow_unsafe_democertificates` setting
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/tools/democonfig/Certificates.java
  src/test/java/org/opensearch/security/tools/democonfig/CertificateGeneratorTests.java
Labels: backport 2.x

#4605 Refactor security provider instantiation
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
Labels: backport 2.x
