Repository opensearch-project/security, pull requests merged in 2024-05, with the labels that each got.

#4307 Release notes for 2.14
  release-notes/opensearch-security.release-notes-2.14.0.0.md
Labels: backport 2.x, backport 2.14

#4252 REST API tests refactoring (Part 2)
  src/integrationTest/java/org/opensearch/security/api/SslCertsRestApiIntegrationTest.java
  src/integrationTest/java/org/opensearch/test/framework/certificate/TestCertificates.java
  src/integrationTest/java/org/opensearch/test/framework/cluster/LocalCluster.java
  src/integrationTest/java/org/opensearch/test/framework/cluster/LocalOpenSearchCluster.java
  src/main/java/org/opensearch/security/ssl/OpenSearchSecuritySSLPlugin.java
  src/main/java/org/opensearch/security/ssl/SecurityKeyStore.java
  src/test/java/org/opensearch/security/dlic/rest/api/SslCertsApiTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/legacy/LegacySslCertsApiTest.java
Labels: backport 2.x

#4255 REST API tests refactoring (Part 4)
  src/integrationTest/java/org/opensearch/security/api/ConfigRestApiIntegrationTest.java
  src/integrationTest/java/org/opensearch/security/api/DefaultApiAvailabilityIntegrationTest.java
  src/integrationTest/java/org/opensearch/security/api/PatchPayloadHelper.java
  src/test/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiActionTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/legacy/LegacySecurityConfigApiActionTests.java
Labels: backport 2.x

#4329 Fix flaky tests
  src/integrationTest/java/org/opensearch/test/framework/cluster/LocalOpenSearchCluster.java
Labels: backport 2.x

#4333 Updating security reachout email
  README.md
  SECURITY.md
Labels: backport 1.x, backport 1.3, backport 2.x

#4340 [Backport 1.x] Updating security reachout email (#4333)
  README.md
  SECURITY.md
Labels: backport 1.3

#4299 [Fix #4280] Introduce new endpoint _plugins/_security/api/certificates
  src/integrationTest/java/org/opensearch/security/api/AbstractApiIntegrationTest.java
  src/integrationTest/java/org/opensearch/security/api/CertificatesRestApiIntegrationTest.java
  src/integrationTest/java/org/opensearch/security/api/SslCertsRestApiIntegrationTest.java
  src/integrationTest/java/org/opensearch/test/framework/cluster/LocalOpenSearchCluster.java
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/dlic/rest/api/CertificatesApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/SecurityRestApiActions.java
  src/main/java/org/opensearch/security/dlic/rest/api/SecuritySSLCertsApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/ssl/CertificateInfo.java
  src/main/java/org/opensearch/security/dlic/rest/api/ssl/CertificateType.java
  src/main/java/org/opensearch/security/dlic/rest/api/ssl/CertificatesActionType.java
  src/main/java/org/opensearch/security/dlic/rest/api/ssl/CertificatesInfo.java
  src/main/java/org/opensearch/security/dlic/rest/api/ssl/CertificatesInfoNodesRequest.java
  src/main/java/org/opensearch/security/dlic/rest/api/ssl/CertificatesNodesResponse.java
  src/main/java/org/opensearch/security/dlic/rest/api/ssl/TransportCertificatesInfoNodesAction.java
Labels: backport 2.x

#4359 Support multiple audience for jwt authentication
  src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java
  src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java
  src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/JwtVerifier.java
  src/test/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticatorTest.java
  src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/HTTPJwtKeyByOpenIdConnectAuthenticatorTest.java
Labels: backport 2.x

#4366 Bump commons-cli to 1.8.0
  build.gradle
  src/main/java/org/opensearch/security/tools/SecurityAdmin.java
Labels: dependencies, backport 2.x, java

#4367 Made sensitive header log statement more clear
  src/main/java/org/opensearch/security/auditlog/config/AuditConfig.java
Labels: backport 2.x

#4375 Bump gradle to 8.7 version
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
Labels: backport 2.x

#4382 Adds 1.3.17.0 release notes
  release-notes/opensearch-security.release-notes-1.3.17.0.md
Labels: backport 1.x, backport 1.3, backport 2.x
