Repository opensearch-project/security, pull requests merged in 2024-11, with the labels that each got.

#4901 Log io.netty.internal.tcnative.SSLContext availability warning only when OpenSSL is explicitly enabled but not available
  src/main/java/org/opensearch/security/ssl/SslSettingsManager.java
Labels: bug, v3.0.0, backport 2.x, v2.19.0

#4913 Reduce log level in HttpJwtAuthenticator if request cannot be authenticated
  src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java
Labels: backport 2.x

#4919 Explicitly create index before ingesting document in ComplianceAuditlogTest.testWriteLogDiffsEnabledAndLogRequestBodyDisabled
  src/test/java/org/opensearch/security/auditlog/compliance/ComplianceAuditlogTest.java
Labels: backport 2.x

#4920 Update Gradle to 8.11
  gradle/wrapper/gradle-wrapper.properties
Labels: backport 2.x

#4924 Update Gradle to 8.11.1
  gradle/wrapper/gradle-wrapper.properties
Labels: backport 2.x

#4880 Add support for certificates hot reload
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/ssl/SslContextHandler.java
  src/main/java/org/opensearch/security/ssl/SslSettingsManager.java
  src/main/java/org/opensearch/security/support/ConfigConstants.java
  src/test/java/org/opensearch/security/ssl/CertificatesRule.java
  src/test/java/org/opensearch/security/ssl/SslSettingsManagerReloadListenerTest.java
  src/test/java/org/opensearch/security/ssl/config/JdkSslCertificatesLoaderTest.java
  src/test/resources/log4j2-test.properties
Labels: backport 2.x, v2.19.0
