Repository opensearch-project/security, pull requests merged in 2024-02, with the labels that each got.

#3920 Add additional sendRequestDecorate cases
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/transport/SecurityInterceptor.java
  src/test/java/org/opensearch/security/transport/SecurityInterceptorTests.java
Labels: backport 2.x

#4006 Admin role for Query insights plugin
  config/roles.yml
Labels: backport 2.x

#4024 Redact sensitive configuration values when retrieving security configuration
  src/integrationTest/java/org/opensearch/security/http/LdapAuthenticationTest.java
  src/main/java/org/opensearch/security/DefaultObjectMapper.java
  src/main/java/org/opensearch/security/dlic/rest/api/AbstractApiAction.java
  src/main/java/org/opensearch/security/securityconf/impl/SecurityDynamicConfiguration.java
Labels: backport 2.x

#4030 Add release notes for 2.12.0.0
  release-notes/opensearch-security.release-notes-2.12.0.0.md
Labels: backport 2.x, backport 2.12

#4027 v2.12 update roles.yml with new API for experimental alerting plugin feature
  config/roles.yml
Labels: backport 2.x

#4025 Add `exclude_roles` configuration parameter to LDAP authorization backend
  src/main/java/com/amazon/dlic/auth/ldap/backend/LDAPAuthorizationBackend.java
  src/main/java/com/amazon/dlic/auth/ldap/util/ConfigConstants.java
  src/main/java/com/amazon/dlic/auth/ldap/util/LdapHelper.java
  src/main/java/com/amazon/dlic/auth/ldap2/LDAPAuthorizationBackend2.java
  src/main/java/org/opensearch/security/support/WildcardMatcher.java
  src/test/java/com/amazon/dlic/auth/ldap/LdapBackendTest.java
  src/test/java/com/amazon/dlic/auth/ldap2/LdapBackendTestNewStyleConfig2.java
  src/test/java/org/opensearch/security/UtilTests.java
Labels: backport 2.x

#4049 Add exlusion for logback-core to resolve CVE-2023-6378
  build.gradle
Labels: backport 2.x

#4052 Update Bouncy Castle Version from *jdk15to18 to *jdk18on
  build.gradle
Labels: backport 1.3, backport 2.x

#4061 Regenerates root-ca, kirk and esnode certificates to address already expired root ca certificate
  DEVELOPER_GUIDE.md
  bwc-test/src/test/resources/security/esnode.pem
  bwc-test/src/test/resources/security/kirk.pem
  bwc-test/src/test/resources/security/root-ca.pem
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/tools/democonfig/Certificates.java
  src/test/java/org/opensearch/security/tools/democonfig/CertificateGeneratorTests.java
  src/test/resources/sanity-tests/kirk-keystore.jks
  src/test/resources/sanity-tests/root-ca.pem
Labels: backport 2.x

#4067 Redact sensitive URL parameters from audit logging
  src/integrationTest/java/org/opensearch/security/http/JwtAuthenticationWithUrlParamTests.java
  src/integrationTest/java/org/opensearch/test/framework/AuditFilters.java
  src/integrationTest/java/org/opensearch/test/framework/audit/AuditMessagePredicate.java
  src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java
  src/main/java/org/opensearch/security/auditlog/config/AuditConfig.java
  src/main/java/org/opensearch/security/auditlog/impl/AbstractAuditLog.java
  src/main/java/org/opensearch/security/auditlog/impl/AuditMessage.java
  src/main/java/org/opensearch/security/auth/HTTPAuthenticator.java
  src/main/java/org/opensearch/security/rest/SecurityInfoAction.java
  src/test/java/org/opensearch/security/auditlog/config/AuditConfigSerializeTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/AuditApiActionTest.java
Labels: backport 2.x

#4053 Add deprecate message that TLSv1 and TLSv1.1 support will be removed in the next major version
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/ssl/util/SSLConfigConstants.java
  src/test/java/org/opensearch/security/ssl/util/SSLConfigConstantsTest.java
Labels: breaking

#4071 Log password requirement details in demo environment
  src/main/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurer.java
  src/test/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurerTests.java
Labels: backport 2.x
