Repository opensearch-project/security, pull requests merged in 2024-04, with the labels that each got.

#4203 Remove date from release notes
  release-notes/opensearch-security.release-notes-2.13.0.0.md
Labels: backport 2.x, backport 2.13

#4152 Adds saml auth header to differentiate saml requests and prevents auto login as anonymous user when basic authentication fails
  src/integrationTest/java/org/opensearch/security/http/BasicWithAnonymousAuthTests.java
  src/main/java/org/opensearch/security/auth/BackendRegistry.java
  src/main/java/org/opensearch/security/rest/SecurityInfoAction.java
Labels: backport 2.x

#4229 Add index permissions for query insights exporters
  config/roles.yml
Labels: backport 2.x

#4232 Handle exceptions for adding request body audit log if rest request is invalid
  src/main/java/org/opensearch/security/auditlog/impl/AuditMessage.java
  src/test/java/org/opensearch/security/auditlog/impl/AuditMessageTest.java
Labels: backport 2.x

#4263 Adds 1.3.16.0 release notes
  release-notes/opensearch-security.release-notes-1.3.16.0.md
Labels: v1.3.16

#4233 Ensure that challenge response contains body
  src/integrationTest/java/org/opensearch/security/ResourceFocusedTests.java
  src/integrationTest/java/org/opensearch/security/http/BasicAuthTests.java
  src/main/java/org/opensearch/security/http/HTTPBasicAuthenticator.java
Labels: backport 2.x

#4269 Add getProperty.org.bouncycastle.ec.max_f2m_field_size to plugin-security.policy
  plugin-security.policy
Labels: backport 2.x

#4275 Replace bouncy castle blake2b
  build.gradle
  src/main/java/org/opensearch/security/configuration/MaskedField.java
  src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java
Labels: backport 2.x

#4253 REST API tests refactoring (Part 3)
  src/test/java/org/opensearch/security/dlic/rest/api/SecurityHealthActionTest.java
  src/test/java/org/opensearch/security/dlic/rest/api/legacy/LegacySecurityHealthActionTests.java
Labels: backport 2.x
