Repository opensearch-project/security, pull requests merged in 2025-08, with the labels that each got.

#5538 [Backport 2.19] Use FilterLeafReader based DLS for parent/child queries
  src/integrationTest/java/org/opensearch/security/ParentChildRelationTests.java
  src/main/java/org/opensearch/security/configuration/DlsFilterLevelActionHandler.java
  src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java
  src/main/java/org/opensearch/security/support/ConfigConstants.java
  src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java
  src/main/java/org/opensearch/security/util/ParentChildrenQueryDetector.java
  src/test/java/org/opensearch/security/util/ParentChildrenQueryDetectorTest.java
Labels: skip-changelog

#5542 Bump gradle to 8.14.3 and move gRPC transport out of experimental
  gradle/wrapper/gradle-wrapper.properties
  src/integrationTest/java/org/opensearch/security/grpc/GrpcClientAuthNoneTests.java
  src/integrationTest/java/org/opensearch/security/grpc/GrpcClientAuthOptionalTests.java
  src/integrationTest/java/org/opensearch/security/grpc/GrpcClientAuthRequireTests.java
  src/integrationTest/java/org/opensearch/security/grpc/GrpcHelpers.java
Labels: skip-changelog

#5530 Integration of security with stream transport
  CHANGELOG.md
  src/main/java/org/opensearch/security/ssl/transport/SecuritySSLRequestHandler.java
  src/main/java/org/opensearch/security/transport/SecurityInterceptor.java
  src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java
  src/test/java/org/opensearch/security/transport/SecurityInterceptorTests.java
Labels: v3.2.0

#5459 [Resource Sharing] Adds a Share API to fetch and update sharing information
  CHANGELOG.md
  sample-resource-plugin/src/integrationTest/java/org/opensearch/sample/resource/ShareApiTests.java
  sample-resource-plugin/src/integrationTest/java/org/opensearch/sample/resource/TestUtils.java
  spi/src/main/java/org/opensearch/security/spi/resources/sharing/Recipients.java
  spi/src/main/java/org/opensearch/security/spi/resources/sharing/ShareWith.java
  spi/src/test/java/org/opensearch/security/spi/resources/ShareWithTests.java
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/dlic/rest/support/Utils.java
  src/main/java/org/opensearch/security/privileges/ResourceAccessEvaluator.java
  src/main/java/org/opensearch/security/resources/ResourceAccessHandler.java
  src/main/java/org/opensearch/security/resources/ResourceSharingIndexHandler.java
  src/main/java/org/opensearch/security/resources/api/share/ShareAction.java
  src/main/java/org/opensearch/security/resources/api/share/ShareRequest.java
  src/main/java/org/opensearch/security/resources/api/share/ShareResponse.java
  src/main/java/org/opensearch/security/resources/api/share/ShareRestAction.java
  src/main/java/org/opensearch/security/resources/api/share/ShareTransportAction.java
  src/test/java/org/opensearch/security/resources/ResourceAccessHandlerTest.java
Labels: resource-permissions, v3.2.0

#5555 Bumps spotbugs to 6.2.4 and checkstyle to 11.0.0
  CHANGELOG.md
  build.gradle
Labels: backport 3.2

#5558 Remove `commons-io` and `commons-lang3` maven metadata from being shaded in opensaml jar
  CHANGELOG.md
  libs/opensaml/build.gradle
Labels: backport 3.2

#5577 fix: Update System.env syntax for Gradle 9 compatibility
  build.gradle
  spi/build.gradle
Labels: skip-changelog

#5591 Remove https://aws.oss.sonatype.org/content/repositories/snapshots from maven repositories
  .github/workflows/ci.yml
  build.gradle
  bwc-test/build.gradle
  bwc-test/src/test/java/org/opensearch/security/bwc/SecurityBackwardsCompatibilityIT.java
  libs/opensaml/build.gradle
  sample-resource-plugin/build.gradle
  spi/build.gradle
  src/main/java/org/opensearch/security/dlic/rest/api/ssl/CertificateInfo.java
  src/main/java/org/opensearch/security/dlic/rest/api/ssl/CertificatesInfo.java
  src/main/java/org/opensearch/security/dlic/rest/api/ssl/CertificatesInfoNodesRequest.java
  src/main/java/org/opensearch/security/dlic/rest/api/ssl/TransportCertificatesInfoNodesAction.java
Labels: skip-changelog
