Repository opensearch-project/security, pull requests merged in 2025-06, with the labels that each got.

#5384 Set git attributes to union changes in the CHANGELOG to reduce merge conflicts
  .gitattributes
Labels: skip-changelog

#5370 Easing debugging for security not initialized error
  CHANGELOG.md
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/auth/BackendRegistry.java
  src/main/java/org/opensearch/security/configuration/ClusterInfoHolder.java
  src/main/java/org/opensearch/security/filter/SecurityFilter.java
  src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
  src/main/java/org/opensearch/security/securityconf/DynamicConfigFactory.java
  src/test/java/org/opensearch/security/configuration/ClusterInfoHolderTest.java
  src/test/java/org/opensearch/security/filter/SecurityFilterTests.java
  src/test/java/org/opensearch/security/privileges/PrivilegesEvaluatorUnitTest.java
  src/test/java/org/opensearch/security/privileges/RestLayerPrivilegesEvaluatorTest.java
Labels: v3.1.0

#5374 Extracted ActionPrivileges interface and created RoleBasedActionPrivileges implementation and SubjectBasedActionPrivileges implementation
  src/integrationTest/java/org/opensearch/security/privileges/IndexPatternTest.java
  src/integrationTest/java/org/opensearch/security/privileges/RestEndpointPermissionTests.java
  src/integrationTest/java/org/opensearch/security/privileges/TenantPrivilegesTest.java
  src/integrationTest/java/org/opensearch/security/privileges/actionlevel/EmptyActionPrivilegesTest.java
  src/integrationTest/java/org/opensearch/security/privileges/actionlevel/RoleBasedActionPrivilegesTest.java
  src/integrationTest/java/org/opensearch/security/privileges/actionlevel/SubjectBasedActionPrivilegesTest.java
  src/integrationTest/java/org/opensearch/security/privileges/dlsfls/DlsFlsLegacyHeadersTest.java
  src/integrationTest/java/org/opensearch/security/privileges/dlsfls/DocumentPrivilegesTest.java
  src/integrationTest/java/org/opensearch/security/privileges/dlsfls/FieldMaskingTest.java
  src/integrationTest/java/org/opensearch/security/privileges/dlsfls/FieldPrivilegesTest.java
  src/integrationTest/java/org/opensearch/security/util/MockPrivilegeEvaluationContextBuilder.java
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/configuration/SystemIndexSearcherWrapper.java
  src/main/java/org/opensearch/security/filter/SecurityFilter.java
  src/main/java/org/opensearch/security/privileges/ActionPrivileges.java
  src/main/java/org/opensearch/security/privileges/IndexPattern.java
  src/main/java/org/opensearch/security/privileges/PrivilegesEvaluationContext.java
  src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
  src/main/java/org/opensearch/security/privileges/RestLayerPrivilegesEvaluator.java
  src/main/java/org/opensearch/security/privileges/actionlevel/RoleBasedActionPrivileges.java
  src/main/java/org/opensearch/security/privileges/actionlevel/RuntimeOptimizedActionPrivileges.java
  src/main/java/org/opensearch/security/privileges/actionlevel/SubjectBasedActionPrivileges.java
  src/main/java/org/opensearch/security/privileges/actionlevel/WellKnownActions.java
  src/main/java/org/opensearch/security/securityconf/impl/v7/RoleV7.java
  src/test/java/org/opensearch/security/privileges/PrivilegesEvaluatorUnitTest.java
  src/test/java/org/opensearch/security/privileges/RestLayerPrivilegesEvaluatorTest.java
  src/test/java/org/opensearch/security/privileges/SystemIndexAccessEvaluatorTest.java
Labels: skip-changelog

#5405 add missing cluster:monitor permission
  config/roles.yml
  release-notes/opensearch-security.release-notes-3.1.0.0.md
Labels: backport 3.1

#5409 Bump com.github.spotbugs from 5.2.5 to 6.3.0 and checkstyle to 10.25.0
  CHANGELOG.md
  build.gradle
Labels: backport 3.1

#5412 add missing mapping get permission
  config/roles.yml
  release-notes/opensearch-security.release-notes-3.1.0.0.md
Labels: skip-changelog, backport 3.1

#5418 [Backport 3.1] Added getter for originalRequest field in IndexResolverReplacer.Resovled
  src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java
Labels: skip-changelog

#5419 Update the maven snapshot publish endpoint and credential
  .github/workflows/maven-publish.yml
  build.gradle
  bwc-test/build.gradle
  sample-resource-plugin/build.gradle
  spi/build.gradle
Labels: skip-changelog

#5432 Provide SecureHttpTransportParameters to complement SecureTransportParameters counterpart
  CHANGELOG.md
  src/main/java/org/opensearch/security/ssl/OpenSearchSecureSettingsFactory.java
Labels: bug, v3.2.0

#5444 Only define opensearch_version in rootProject build.gradle file and remove other duplication
  bwc-test/build.gradle
  bwc-test/settings.gradle
  sample-resource-plugin/build.gradle
  settings.gradle
  spi/build.gradle
Labels: skip-changelog
