Repository opensearch-project/security, pull requests merged in 2025-04, with the labels that each got.

#5185 [Resource Access Control] [Part1] Introduces SPI for resource access control
  .github/workflows/ci.yml
  .github/workflows/maven-publish.yml
  .gitignore
  build.gradle
  scripts/build.sh
  settings.gradle
  spi/README.md
  spi/build.gradle
  spi/src/main/java/org/opensearch/security/spi/resources/ResourceAccessActionGroups.java
  spi/src/main/java/org/opensearch/security/spi/resources/ResourceSharingExtension.java
  spi/src/main/java/org/opensearch/security/spi/resources/ShareableResource.java
  spi/src/main/java/org/opensearch/security/spi/resources/ShareableResourceParser.java
  spi/src/main/java/org/opensearch/security/spi/resources/package-info.java
  spi/src/main/java/org/opensearch/security/spi/resources/sharing/CreatedBy.java
  spi/src/main/java/org/opensearch/security/spi/resources/sharing/Creator.java
  spi/src/main/java/org/opensearch/security/spi/resources/sharing/Recipient.java
  spi/src/main/java/org/opensearch/security/spi/resources/sharing/ResourceSharing.java
  spi/src/main/java/org/opensearch/security/spi/resources/sharing/ShareWith.java
  spi/src/main/java/org/opensearch/security/spi/resources/sharing/SharedWithActionGroup.java
  spi/src/test/java/org/opensearch/security/spi/resources/CreatedByTests.java
  spi/src/test/java/org/opensearch/security/spi/resources/ShareWithTests.java
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
  src/main/java/org/opensearch/security/support/ConfigConstants.java
Labels: resource-permissions

#5299 Remove beta1 qualifier
  .github/workflows/plugin_install.yml
  build.gradle
Labels: release, v3.0.0, backport main

#5303 Corrections in DlsFlsFilterLeafReader regarding PointVales and object valued attributes
  src/integrationTest/java/org/opensearch/security/privileges/dlsfls/FieldPrivilegesTest.java
  src/integrationTest/java/org/opensearch/security/privileges/dlsfls/FlsFmIntegrationTests.java
  src/integrationTest/java/org/opensearch/test/framework/TestData.java
  src/integrationTest/java/org/opensearch/test/framework/matcher/RestDocumentMatchers.java
  src/integrationTest/java/org/opensearch/test/framework/matcher/RestMatchers.java
  src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java
  src/main/java/org/opensearch/security/configuration/DlsFlsValveImpl.java
  src/main/java/org/opensearch/security/privileges/dlsfls/FieldPrivileges.java
  src/main/java/org/opensearch/security/privileges/dlsfls/FlsDocumentFilter.java
  src/main/java/org/opensearch/security/privileges/dlsfls/FlsStoredFieldVisitor.java
Labels: backport 3.0
