Repository opensearch-project/security, pull requests merged in 2025-02, with the labels that each got.

#5077 [Backport 2.19] Update `restPathMatches` to handle case with missing leading slash (#5061)
  src/integrationTest/java/org/opensearch/security/rest/WhoAmITests.java
  src/integrationTest/java/org/opensearch/test/framework/cluster/TestRestClient.java
  src/main/java/org/opensearch/security/filter/SecurityRestFilter.java
  src/test/java/org/opensearch/security/filter/RestPathMatchesTests.java
  src/test/java/org/opensearch/security/filter/SecurityRestFilterUnitTests.java
Labels: backport 2.x

#5076 Ensure that IndexResolverReplacer resolves to indices for RolloverRequests
  src/integrationTest/java/org/opensearch/security/RolloverTest.java
  src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java
Labels: backport 2.x

#5084 [2.x] Avoid ConcurrentModificationException for User class fields
  src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java
Labels: backport main

#4882 Extended /certificates endpoint with additional SSL certs info
  src/integrationTest/java/org/opensearch/security/api/CertificatesRestApiIntegrationTest.java
  src/main/java/org/opensearch/security/dlic/rest/api/CertificatesApiAction.java
  src/main/java/org/opensearch/security/dlic/rest/api/ssl/CertificateInfo.java
  src/main/java/org/opensearch/security/dlic/rest/api/ssl/CertificateType.java
  src/main/java/org/opensearch/security/dlic/rest/api/ssl/CertificatesInfo.java
  src/main/java/org/opensearch/security/dlic/rest/api/ssl/CertificatesInfoNodesRequest.java
  src/main/java/org/opensearch/security/dlic/rest/api/ssl/TransportCertificatesInfoNodesAction.java
  src/main/java/org/opensearch/security/ssl/SslContextHandler.java
  src/main/java/org/opensearch/security/ssl/config/CertType.java
  src/main/java/org/opensearch/security/ssl/config/Certificate.java
Labels: backport 2.x

#5116 Fix ssl hot reload settings
  src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
Labels: backport 2.x, backport 2.19

#5133 Update Andriy Redko (https://github.com/reta) affiliation
  MAINTAINERS.md
Labels: backport 2.x

#5138 Add release notes for 2.19.1
  release-notes/opensearch-security.release-notes-2.19.1.0.md
Labels: backport 2.x, backport 2.19

#5141 [2.x] Update common_utils version
  build.gradle
  bwc-test/build.gradle
Labels: backport 2.19
